/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/auth/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register a new user */
		post: operations['register'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Login with email and password */
		post: operations['login'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current user and workspace info */
		get: operations['getMe'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Logout current session */
		post: operations['logout'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/deployments': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create a new deployment */
		post: operations['createDeployment'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/deployments/{id}/logs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Stream deployment logs via SSE
		 * @description Returns a Server-Sent Events stream. OpenAPI does not natively model SSE,
		 *     so this endpoint is documented for reference only.
		 *
		 *     **SSE events (not modeled by this schema):**
		 *     - Default message event: JSON-encoded LogEntry
		 *     - `done` event: deployment final status string ("success" or "failed")
		 *     - `stream-error` event: JSON object with "message" field
		 */
		get: operations['getDeploymentLogs'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/servers': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List registered servers */
		get: operations['listServers'];
		put?: never;
		/** Register a new server */
		post: operations['createServer'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/servers/{id}/proxy-logs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Stream the reverse proxy's logs via SSE
		 * @description Returns a Server-Sent Events stream of Traefik's output on this server —
		 *     its own startup and certificate messages, and one access-log line per
		 *     request it routes. OpenAPI does not natively model SSE, so this endpoint
		 *     is documented for reference only.
		 *
		 *     This is per server rather than per service: one proxy answers for every
		 *     service on the machine, so the log is one stream and the service a line
		 *     belongs to is named in the line itself.
		 *
		 *     **SSE events (not modeled by this schema):**
		 *     - Default message event: JSON object with "output" and "type" ("stdout" or "stderr")
		 *     - `done` event: the proxy's stream ended
		 *     - `stream-error` event: JSON object with "message" field
		 */
		get: operations['getProxyLogs'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/servers/{id}/proxy': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Install or upgrade the managed Traefik proxy */
		post: operations['upgradeServerProxy'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List projects in workspace */
		get: operations['listProjects'];
		put?: never;
		/** Create a new project */
		post: operations['createProject'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/from-image': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create a project, default environment, and Docker image service atomically */
		post: operations['createProjectFromImage'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get project details */
		get: operations['getProject'];
		/** Update project */
		put: operations['updateProject'];
		post?: never;
		/** Delete a project */
		delete: operations['deleteProject'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{id}/environments': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List environments in a project */
		get: operations['listEnvironments'];
		put?: never;
		/** Create a new environment in a project */
		post: operations['createEnvironment'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{id}/environments/{envId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get environment details */
		get: operations['getEnvironment'];
		/** Update environment */
		put: operations['updateEnvironment'];
		post?: never;
		/** Delete an environment */
		delete: operations['deleteEnvironment'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{id}/services': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List services in a project */
		get: operations['listProjectServices'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/projects/{id}/observability': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current project container metrics */
		get: operations['getProjectObservability'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/services': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List services in workspace */
		get: operations['listServices'];
		put?: never;
		/** Create a new service */
		post: operations['createService'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/services/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get service details */
		get: operations['getService'];
		/** Update service configuration */
		put: operations['updateService'];
		post?: never;
		/** Delete a service */
		delete: operations['deleteService'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/services/{id}/logs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Stream a running container's logs via SSE
		 * @description Returns a Server-Sent Events stream of the service's container output,
		 *     starting with the last 200 lines and then following live. OpenAPI does
		 *     not natively model SSE, so this endpoint is documented for reference only.
		 *
		 *     Unlike deployment logs these are not stored by Uploy — Docker holds the
		 *     history, so a reconnect re-tails rather than resuming.
		 *
		 *     **SSE events (not modeled by this schema):**
		 *     - Default message event: JSON object with "output" and "type" ("stdout" or "stderr")
		 *     - `done` event: the container's stream ended
		 *     - `stream-error` event: JSON object with "message" field
		 */
		get: operations['getServiceLogs'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/services/{id}/envs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List environment variables for a service */
		get: operations['listServiceEnvs'];
		put?: never;
		/** Set or update an environment variable */
		post: operations['upsertServiceEnv'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/services/{id}/envs/{key}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete an environment variable */
		delete: operations['deleteServiceEnv'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/services/{id}/deployments': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List deployment history for a service */
		get: operations['listServiceDeployments'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/services/{id}/pending-changes': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List the changes waiting to be deployed for a service
		 * @description Itemises what the running container would have to change to match the service as it is configured now. Owner and developer only: the list carries environment variable values, which is the same reason listServiceEnvs is gated.
		 */
		get: operations['getServicePendingChanges'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/services/{id}/domains': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List domains for a service */
		get: operations['listServiceDomains'];
		put?: never;
		/** Add a domain to a service */
		post: operations['createServiceDomain'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/services/{id}/domains/{domainId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Update domain settings */
		put: operations['updateServiceDomain'];
		post?: never;
		/** Remove a domain from a service */
		delete: operations['deleteServiceDomain'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/servers/check-connection': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Test SSH connectivity to a server */
		post: operations['checkConnection'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/ssh-keys': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List stored SSH keys */
		get: operations['listSSHKeys'];
		put?: never;
		/** Store an SSH private key */
		post: operations['createSSHKey'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/ssh-keys/generate': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Generate a new Ed25519 SSH keypair */
		post: operations['generateSSHKey'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		LoginRequest: {
			/** Format: email */
			email: string;
			password: string;
		};
		User: {
			id: string;
			/** Format: email */
			email: string;
			platform_role: string;
		};
		Workspace: {
			id: string;
			name: string;
			role?: string;
		};
		AuthResponse: {
			user: components['schemas']['User'];
			workspace: components['schemas']['Workspace'];
		};
		LogoutResponse: {
			ok: boolean;
		};
		DeployRequest: {
			service_id: string;
		};
		DeployResponse: {
			deployment_id: string;
		};
		DeploymentResponse: {
			id: string;
			/** @enum {string} */
			status: 'in_progress' | 'success' | 'failed';
			service_id: string;
			/** Format: date-time */
			created_at: string;
			phase: string;
			is_active: boolean;
			is_draining: boolean;
			is_rolling: boolean;
		};
		ErrorResponse: {
			error: string;
			/**
			 * @description Machine-readable failure stage. Present on SSH probe failures so a client can offer the right remedy: the three stages need entirely different fixes, and the human message alone cannot be branched on.
			 * @enum {string}
			 */
			code?: 'unreachable' | 'key_rejected' | 'key_invalid' | 'session_failed' | 'docker_missing';
		};
		CreateSSHKeyRequest: {
			name: string;
			private_key: string;
		};
		GenerateSSHKeyRequest: {
			name: string;
		};
		CheckConnectionRequest: {
			host: string;
			/** @default 22 */
			port: number;
			ssh_user: string;
			ssh_key_id: string;
		};
		CheckConnectionResponse: {
			ok: boolean;
		};
		SSHKeyResponse: {
			id: string;
			name: string;
			/** @description OpenSSH authorized_keys format public key derived from the stored private key */
			public_key: string;
			/** Format: date-time */
			created_at: string;
		};
		CreateServerRequest: {
			name: string;
			host: string;
			/** @default 22 */
			port: number;
			ssh_user: string;
			ssh_key_id: string;
		};
		ServerResponse: {
			id: string;
			name: string;
			host: string;
			port: number;
			ssh_user: string;
			ssh_key_id: string;
			/** @enum {string} */
			proxy_status: 'not_configured' | 'ready' | 'port_conflict' | 'degraded';
			/** Format: date-time */
			proxy_last_reconciled_at?: string;
			proxy_last_error?: string;
			/** Format: date-time */
			created_at: string;
		};
		LogEntry: {
			/** Format: int64 */
			id: number;
			order: number;
			/** Format: date-time */
			created_at: string;
			output: string;
			/** @enum {string} */
			type: 'stdout' | 'stderr';
			/** @description Structured deploy phase identifier. Empty string for raw command output. */
			phase: string;
		};
		ProjectResponse: {
			id: string;
			name: string;
			workspace_id: string;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
		};
		/**
		 * @description Request body for creating a project. When `name` is omitted, blank, or
		 *     whitespace-only, the backend generates a unique Railway-style
		 *     `adjective-noun` name scoped to the workspace.
		 */
		CreateProjectRequest: {
			name?: string;
		};
		UpdateProjectRequest: {
			name: string;
		};
		CreateProjectFromImageRequest: {
			server_id: string;
			/** @description Docker image reference, e.g. `nginx:latest` or `ghcr.io/owner/repo:tag`. */
			image: string;
			/** @description Container port the service listens on. */
			container_port: number;
			/** @description Host port the service is published on. Omit to keep the service internal — reachable by other services on the uploy network and by nothing outside the machine, which is what a database wants. 80 and 443 are rejected: they belong to the Uploy proxy. Ignored while the service has a domain, since that traffic goes through the proxy. */
			host_port?: number;
		};
		CreateProjectFromImageResponse: {
			project: components['schemas']['ProjectResponse'];
			environment: components['schemas']['EnvironmentResponse'];
			service: components['schemas']['ServiceResponse'];
		};
		EnvironmentResponse: {
			id: string;
			name: string;
			project_id: string;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
		};
		CreateEnvironmentRequest: {
			name: string;
		};
		UpdateEnvironmentRequest: {
			name: string;
		};
		CreateServiceRequest: {
			name: string;
			image: string;
			container_name: string;
			/** @description Container port the image listens on. */
			container_port: number;
			/** @description Host port the service is published on. Omit to keep the service internal — reachable by other services on the uploy network and by nothing outside the machine, which is what a database wants. 80 and 443 are rejected: they belong to the Uploy proxy. Ignored while the service has a domain, since that traffic goes through the proxy. */
			host_port?: number;
			server_id: string;
			environment_id: string;
			/**
			 * @default application
			 * @enum {string}
			 */
			kind: 'application';
		};
		UpdateServiceRequest: {
			name: string;
			image: string;
			container_name: string;
			/** @description Container port the image listens on. */
			container_port: number;
			/** @description Host port the service is published on. Omit to keep the service internal — reachable by other services on the uploy network and by nothing outside the machine, which is what a database wants. 80 and 443 are rejected: they belong to the Uploy proxy. Ignored while the service has a domain, since that traffic goes through the proxy. */
			host_port?: number;
			server_id: string;
		};
		ServiceResponse: {
			id: string;
			name: string;
			image: string;
			container_name: string;
			/** @description Container port the image listens on. */
			container_port: number;
			/** @description Host port the service is published on. Omit to keep the service internal — reachable by other services on the uploy network and by nothing outside the machine, which is what a database wants. 80 and 443 are rejected: they belong to the Uploy proxy. Ignored while the service has a domain, since that traffic goes through the proxy. */
			host_port?: number;
			server_id: string;
			/** @enum {string} */
			kind: 'application';
			project_id: string;
			environment_id: string;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
			/**
			 * @description How many changes are waiting to be deployed: the difference between the service's current configuration and the configuration its last successful deployment actually shipped, counted per field, per domain and per variable. Zero means the running container matches what the service says it is.
			 *     A service with nothing to compare against — never deployed, or last deployed before Uploy recorded configurations — reports 1. It is pending, but there is no itemised answer to give.
			 *     Derived per request, never stored.
			 */
			pending_change_count: number;
			/** @description True once at least one deployment of this service has succeeded. Combined with has_pending_changes it distinguishes a service that will be created on its server from one that will be updated. Derived per request, never stored. */
			has_deployed: boolean;
		};
		ProjectObservabilityResponse: {
			/** Format: date-time */
			sampled_at: string;
			/** @description Recommended client refresh interval. */
			refresh_after_seconds: number;
			summary: components['schemas']['ProjectObservabilitySummary'];
			services: components['schemas']['ServiceObservability'][];
		};
		ProjectObservabilitySummary: {
			total_services: number;
			running_services: number;
			degraded_services: number;
			/** Format: double */
			cpu_percent: number;
			/** Format: int64 */
			memory_used_bytes: number;
			/** Format: int64 */
			memory_limit_bytes: number;
			/** Format: int64 */
			network_in_bytes_total: number;
			/** Format: int64 */
			network_out_bytes_total: number;
		};
		ServiceObservability: {
			service_id: string;
			name: string;
			environment_name: string;
			/** @enum {string} */
			status: 'not_deployed' | 'running' | 'stopped' | 'unreachable' | 'error';
			deployment_id?: string;
			error?: string;
			container?: components['schemas']['ContainerObservability'];
		};
		ContainerObservability: {
			id: string;
			name: string;
			state: string;
			/** Format: double */
			cpu_percent: number;
			/** Format: int64 */
			memory_used_bytes: number;
			/** Format: int64 */
			memory_limit_bytes: number;
			/** Format: int64 */
			network_in_bytes_total: number;
			/** Format: int64 */
			network_out_bytes_total: number;
			/** Format: int64 */
			uptime_seconds: number;
		};
		ConfigChange: {
			/** @description Stable identifier for this change, unique within the list — "image", "domain:app.example.com", "env:DATABASE_URL". */
			key: string;
			/** @description What the change is called in the interface. */
			label: string;
			/** @enum {string} */
			type: 'added' | 'removed' | 'changed';
			/** @description Absent when the thing did not exist before. */
			old_value?: string;
			/** @description Absent when the thing no longer exists. */
			new_value?: string;
		};
		PendingChangesResponse: {
			/** @description False when there is no deployed configuration to compare against: the service has never deployed, or last deployed before Uploy recorded configurations. The service is pending either way, but changes is empty because no itemised answer exists — say so rather than showing an empty list under a badge that says otherwise. */
			has_baseline: boolean;
			changes: components['schemas']['ConfigChange'][];
		};
		CreateDomainRequest: {
			domain: string;
		};
		UpdateDomainRequest: {
			is_primary: boolean;
		};
		ServiceDomainResponse: {
			id: string;
			domain: string;
			is_primary: boolean;
			/** @enum {string} */
			status: 'pending' | 'ready' | 'error';
			last_error?: string;
			/** Format: date-time */
			last_reconciled_at?: string;
			/** Format: date-time */
			ready_at?: string;
			/**
			 * Format: date-time
			 * @description When the reconciler next examines pending domains. A domain cannot change status between two of those passes, so this is the moment a client should wait for. Absent once the domain is ready, or if the reconciler is not running.
			 */
			next_check_at?: string;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
		};
		UpsertEnvRequest: {
			key: string;
			value: string;
		};
		ServiceEnvResponse: {
			/** Format: int64 */
			id: number;
			key: string;
			value: string;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	register: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LoginRequest'];
			};
		};
		responses: {
			/** @description User registered successfully */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Email already registered */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LoginRequest'];
			};
		};
		responses: {
			/** @description Login successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Invalid credentials */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Account not active */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Too many login attempts */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getMe: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current user info */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Logout successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LogoutResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	createDeployment: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DeployRequest'];
			};
		};
		responses: {
			/** @description Deployment created */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DeployResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description The server proxy must be upgraded before a domain deployment */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getDeploymentLogs: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description SSE log stream */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/event-stream': components['schemas']['LogEntry'];
				};
			};
			/** @description Invalid deployment ID format */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Deployment not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	listServers: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of servers */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServerResponse'][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	createServer: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateServerRequest'];
			};
		};
		responses: {
			/** @description Server created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServerResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description SSH connection test failed */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getProxyLogs: {
		parameters: {
			query?: {
				/** @description Only replay history from this far back. Omitted, the stream starts from the last 200 lines however old they are. */
				since?: '1h' | '6h' | '24h' | '7d' | '30d';
			};
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description SSE log stream */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/event-stream': string;
				};
			};
			/** @description `since` is not one of the listed values */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	upgradeServerProxy: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Proxy upgraded and ready for rolling deployments */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServerResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Server not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Proxy installation or upgrade failed */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description The server could not be reached, or has no usable Docker */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	listProjects: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of projects */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProjectResponse'][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	createProject: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: {
			content: {
				'application/json': components['schemas']['CreateProjectRequest'];
			};
		};
		responses: {
			/** @description Project created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProjectResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	createProjectFromImage: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateProjectFromImageRequest'];
			};
		};
		responses: {
			/** @description Project, environment, and service created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CreateProjectFromImageResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Container name already in use on this server */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getProject: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Project details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProjectResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Project not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	updateProject: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateProjectRequest'];
			};
		};
		responses: {
			/** @description Project updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProjectResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Project not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	deleteProject: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Project deleted */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Project not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	listEnvironments: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of environments */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['EnvironmentResponse'][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Project not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	createEnvironment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateEnvironmentRequest'];
			};
		};
		responses: {
			/** @description Environment created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['EnvironmentResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Project not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getEnvironment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				envId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Environment details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['EnvironmentResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Environment not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	updateEnvironment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				envId: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateEnvironmentRequest'];
			};
		};
		responses: {
			/** @description Environment updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['EnvironmentResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Environment not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	deleteEnvironment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				envId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Environment deleted */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Environment not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	listProjectServices: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of services for the project, newest first */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceResponse'][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Project not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getProjectObservability: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current metrics for active project deployments */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProjectObservabilityResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Project not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	listServices: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of services */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceResponse'][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	createService: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateServiceRequest'];
			};
		};
		responses: {
			/** @description Service created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Container name already in use on this server */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getService: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service details */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	updateService: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateServiceRequest'];
			};
		};
		responses: {
			/** @description Service updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	deleteService: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Service deleted */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description The container could not be removed from the server, so the service was kept. Retry once the server is reachable again. */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getServiceLogs: {
		parameters: {
			query?: {
				/** @description Only replay history from this far back. Omitted, the stream starts from the last 200 lines however old they are. */
				since?: '1h' | '6h' | '24h' | '7d' | '30d';
			};
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description SSE log stream */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/event-stream': string;
				};
			};
			/** @description Service has not been deployed yet, or `since` is not one of the listed values */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description The server could not be reached */
			502: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	listServiceEnvs: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of environment variables */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceEnvResponse'][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	upsertServiceEnv: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpsertEnvRequest'];
			};
		};
		responses: {
			/** @description Environment variable set */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceEnvResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	deleteServiceEnv: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				key: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Environment variable deleted */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	listServiceDeployments: {
		parameters: {
			query?: {
				limit?: number;
			};
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of deployments */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DeploymentResponse'][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	getServicePendingChanges: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The pending changes */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PendingChangesResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	listServiceDomains: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of domains */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceDomainResponse'][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	createServiceDomain: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateDomainRequest'];
			};
		};
		responses: {
			/** @description Domain added */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceDomainResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Service not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Domain already in use */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	updateServiceDomain: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				domainId: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateDomainRequest'];
			};
		};
		responses: {
			/** @description Domain updated */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceDomainResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Domain not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	deleteServiceDomain: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				domainId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Domain deleted */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Domain not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	checkConnection: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CheckConnectionRequest'];
			};
		};
		responses: {
			/** @description Connection successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CheckConnectionResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description SSH connection test failed */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	listSSHKeys: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description List of SSH keys */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SSHKeyResponse'][];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	createSSHKey: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateSSHKeyRequest'];
			};
		};
		responses: {
			/** @description SSH key created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SSHKeyResponse'];
				};
			};
			/** @description Invalid request or key */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
	generateSSHKey: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['GenerateSSHKeyRequest'];
			};
		};
		responses: {
			/** @description SSH keypair generated */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SSHKeyResponse'];
				};
			};
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Not authenticated */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Insufficient permissions */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrorResponse'];
				};
			};
		};
	};
}
