// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAlertRuleChannel = `-- name: AddAlertRuleChannel :exec
INSERT INTO alert_rule_channels (rule_id, channel_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddAlertRuleChannelParams struct {
	RuleID    string `json:"rule_id"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) AddAlertRuleChannel(ctx context.Context, arg AddAlertRuleChannelParams) error {
	_, err := q.db.Exec(ctx, addAlertRuleChannel, arg.RuleID, arg.ChannelID)
	return err
}

const createAlertEvent = `-- name: CreateAlertEvent :one
INSERT INTO alert_events (workspace_id, rule_id, target_id, target_name, status, started_at, trigger_value)
VALUES ($1, $2, $3, $4, 'firing', $5, $6)
RETURNING id, workspace_id, rule_id, target_id, target_name, status, started_at, resolved_at, trigger_value, resolved_value, created_at
`

type CreateAlertEventParams struct {
	WorkspaceID  string    `json:"workspace_id"`
	RuleID       string    `json:"rule_id"`
	TargetID     string    `json:"target_id"`
	TargetName   string    `json:"target_name"`
	StartedAt    time.Time `json:"started_at"`
	TriggerValue float64   `json:"trigger_value"`
}

func (q *Queries) CreateAlertEvent(ctx context.Context, arg CreateAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, createAlertEvent,
		arg.WorkspaceID,
		arg.RuleID,
		arg.TargetID,
		arg.TargetName,
		arg.StartedAt,
		arg.TriggerValue,
	)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuleID,
		&i.TargetID,
		&i.TargetName,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.TriggerValue,
		&i.ResolvedValue,
		&i.CreatedAt,
	)
	return i, err
}

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (workspace_id, name, condition, threshold, duration_seconds, scope_type, server_id, service_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, name, condition, threshold, duration_seconds, scope_type, server_id, service_id, enabled, created_at, updated_at
`

type CreateAlertRuleParams struct {
	WorkspaceID     string      `json:"workspace_id"`
	Name            string      `json:"name"`
	Condition       string      `json:"condition"`
	Threshold       float64     `json:"threshold"`
	DurationSeconds int32       `json:"duration_seconds"`
	ScopeType       string      `json:"scope_type"`
	ServerID        pgtype.Text `json:"server_id"`
	ServiceID       pgtype.Text `json:"service_id"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.WorkspaceID,
		arg.Name,
		arg.Condition,
		arg.Threshold,
		arg.DurationSeconds,
		arg.ScopeType,
		arg.ServerID,
		arg.ServiceID,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Condition,
		&i.Threshold,
		&i.DurationSeconds,
		&i.ScopeType,
		&i.ServerID,
		&i.ServiceID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (workspace_id, name, type, config_ciphertext)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, type, config_ciphertext, enabled, created_at, updated_at
`

type CreateNotificationChannelParams struct {
	WorkspaceID      string `json:"workspace_id"`
	Name             string `json:"name"`
	Type             string `json:"type"`
	ConfigCiphertext string `json:"config_ciphertext"`
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.WorkspaceID,
		arg.Name,
		arg.Type,
		arg.ConfigCiphertext,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.ConfigCiphertext,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :exec
DELETE FROM alert_rules WHERE id = $1
`

func (q *Queries) DeleteAlertRule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAlertRule, id)
	return err
}

const deleteAlertRuleChannels = `-- name: DeleteAlertRuleChannels :exec
DELETE FROM alert_rule_channels WHERE rule_id = $1
`

func (q *Queries) DeleteAlertRuleChannels(ctx context.Context, ruleID string) error {
	_, err := q.db.Exec(ctx, deleteAlertRuleChannels, ruleID)
	return err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :exec
DELETE FROM notification_channels WHERE id = $1
`

func (q *Queries) DeleteNotificationChannel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteNotificationChannel, id)
	return err
}

const findActiveAlertEvent = `-- name: FindActiveAlertEvent :one
SELECT id, workspace_id, rule_id, target_id, target_name, status, started_at, resolved_at, trigger_value, resolved_value, created_at
FROM alert_events WHERE rule_id = $1 AND target_id = $2 AND status = 'firing'
ORDER BY started_at DESC LIMIT 1
`

type FindActiveAlertEventParams struct {
	RuleID   string `json:"rule_id"`
	TargetID string `json:"target_id"`
}

func (q *Queries) FindActiveAlertEvent(ctx context.Context, arg FindActiveAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, findActiveAlertEvent, arg.RuleID, arg.TargetID)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuleID,
		&i.TargetID,
		&i.TargetName,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.TriggerValue,
		&i.ResolvedValue,
		&i.CreatedAt,
	)
	return i, err
}

const getAlertRule = `-- name: GetAlertRule :one
SELECT id, workspace_id, name, condition, threshold, duration_seconds, scope_type, server_id, service_id, enabled, created_at, updated_at
FROM alert_rules WHERE id = $1
`

func (q *Queries) GetAlertRule(ctx context.Context, id string) (AlertRule, error) {
	row := q.db.QueryRow(ctx, getAlertRule, id)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Condition,
		&i.Threshold,
		&i.DurationSeconds,
		&i.ScopeType,
		&i.ServerID,
		&i.ServiceID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, workspace_id, name, type, config_ciphertext, enabled, created_at, updated_at
FROM notification_channels WHERE id = $1
`

func (q *Queries) GetNotificationChannel(ctx context.Context, id string) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.ConfigCiphertext,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertEvents = `-- name: ListAlertEvents :many
SELECT id, workspace_id, rule_id, target_id, target_name, status, started_at, resolved_at, trigger_value, resolved_value, created_at
FROM alert_events WHERE workspace_id = $1
ORDER BY started_at DESC LIMIT $2 OFFSET $3
`

type ListAlertEventsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListAlertEvents(ctx context.Context, arg ListAlertEventsParams) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listAlertEvents, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertEvent{}
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RuleID,
			&i.TargetID,
			&i.TargetName,
			&i.Status,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.TriggerValue,
			&i.ResolvedValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRuleChannels = `-- name: ListAlertRuleChannels :many
SELECT channel_id FROM alert_rule_channels WHERE rule_id = $1 ORDER BY channel_id
`

func (q *Queries) ListAlertRuleChannels(ctx context.Context, ruleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAlertRuleChannels, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var channel_id string
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, workspace_id, name, condition, threshold, duration_seconds, scope_type, server_id, service_id, enabled, created_at, updated_at
FROM alert_rules WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAlertRules(ctx context.Context, workspaceID string) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRules, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Condition,
			&i.Threshold,
			&i.DurationSeconds,
			&i.ScopeType,
			&i.ServerID,
			&i.ServiceID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRules = `-- name: ListEnabledAlertRules :many
SELECT id, workspace_id, name, condition, threshold, duration_seconds, scope_type, server_id, service_id, enabled, created_at, updated_at
FROM alert_rules WHERE enabled = TRUE ORDER BY created_at ASC
`

func (q *Queries) ListEnabledAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listEnabledAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Condition,
			&i.Threshold,
			&i.DurationSeconds,
			&i.ScopeType,
			&i.ServerID,
			&i.ServiceID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, workspace_id, name, type, config_ciphertext, enabled, created_at, updated_at
FROM notification_channels WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListNotificationChannels(ctx context.Context, workspaceID string) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Type,
			&i.ConfigCiphertext,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlertEvent = `-- name: ResolveAlertEvent :one
UPDATE alert_events
SET status = 'resolved', resolved_at = $2, resolved_value = $3
WHERE id = $1 AND status = 'firing'
RETURNING id, workspace_id, rule_id, target_id, target_name, status, started_at, resolved_at, trigger_value, resolved_value, created_at
`

type ResolveAlertEventParams struct {
	ID            string             `json:"id"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
	ResolvedValue pgtype.Float8      `json:"resolved_value"`
}

func (q *Queries) ResolveAlertEvent(ctx context.Context, arg ResolveAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, resolveAlertEvent, arg.ID, arg.ResolvedAt, arg.ResolvedValue)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RuleID,
		&i.TargetID,
		&i.TargetName,
		&i.Status,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.TriggerValue,
		&i.ResolvedValue,
		&i.CreatedAt,
	)
	return i, err
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE alert_rules
SET name = $2, condition = $3, threshold = $4, duration_seconds = $5, scope_type = $6,
    server_id = $7, service_id = $8, enabled = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, name, condition, threshold, duration_seconds, scope_type, server_id, service_id, enabled, created_at, updated_at
`

type UpdateAlertRuleParams struct {
	ID              string      `json:"id"`
	Name            string      `json:"name"`
	Condition       string      `json:"condition"`
	Threshold       float64     `json:"threshold"`
	DurationSeconds int32       `json:"duration_seconds"`
	ScopeType       string      `json:"scope_type"`
	ServerID        pgtype.Text `json:"server_id"`
	ServiceID       pgtype.Text `json:"service_id"`
	Enabled         bool        `json:"enabled"`
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, updateAlertRule,
		arg.ID,
		arg.Name,
		arg.Condition,
		arg.Threshold,
		arg.DurationSeconds,
		arg.ScopeType,
		arg.ServerID,
		arg.ServiceID,
		arg.Enabled,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Condition,
		&i.Threshold,
		&i.DurationSeconds,
		&i.ScopeType,
		&i.ServerID,
		&i.ServiceID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels
SET name = $2, type = $3, config_ciphertext = $4, enabled = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, name, type, config_ciphertext, enabled, created_at, updated_at
`

type UpdateNotificationChannelParams struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	Type             string `json:"type"`
	ConfigCiphertext string `json:"config_ciphertext"`
	Enabled          bool   `json:"enabled"`
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannel,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.ConfigCiphertext,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.ConfigCiphertext,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
