// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package sqlcgen

import (
	"context"
	"time"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (name, image, container_name, port, server_id, workspace_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, image, container_name, port, server_id, workspace_id, created_at, updated_at
`

type CreateApplicationParams struct {
	Name          string `json:"name"`
	Image         string `json:"image"`
	ContainerName string `json:"container_name"`
	Port          int32  `json:"port"`
	ServerID      string `json:"server_id"`
	WorkspaceID   string `json:"workspace_id"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.Name,
		arg.Image,
		arg.ContainerName,
		arg.Port,
		arg.ServerID,
		arg.WorkspaceID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.Port,
		&i.ServerID,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, name, image, container_name, port, server_id, workspace_id, created_at, updated_at
FROM applications WHERE id = $1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.Port,
		&i.ServerID,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationWithServer = `-- name: GetApplicationWithServer :one
SELECT
    a.id, a.name, a.image, a.container_name, a.port,
    a.server_id, a.workspace_id, a.created_at, a.updated_at,
    s.host, s.port AS server_port, s.ssh_user,
    s.proxy_status,
    k.private_key
FROM applications a
JOIN servers s ON s.id = a.server_id
JOIN ssh_keys k ON k.id = s.ssh_key_id
WHERE a.id = $1
`

type GetApplicationWithServerRow struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Image         string    `json:"image"`
	ContainerName string    `json:"container_name"`
	Port          int32     `json:"port"`
	ServerID      string    `json:"server_id"`
	WorkspaceID   string    `json:"workspace_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Host          string    `json:"host"`
	ServerPort    int32     `json:"server_port"`
	SshUser       string    `json:"ssh_user"`
	ProxyStatus   string    `json:"proxy_status"`
	PrivateKey    string    `json:"private_key"`
}

func (q *Queries) GetApplicationWithServer(ctx context.Context, id string) (GetApplicationWithServerRow, error) {
	row := q.db.QueryRow(ctx, getApplicationWithServer, id)
	var i GetApplicationWithServerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.Port,
		&i.ServerID,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Host,
		&i.ServerPort,
		&i.SshUser,
		&i.ProxyStatus,
		&i.PrivateKey,
	)
	return i, err
}

const listApplicationsByWorkspace = `-- name: ListApplicationsByWorkspace :many
SELECT id, name, image, container_name, port, server_id, workspace_id, created_at, updated_at
FROM applications WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListApplicationsByWorkspace(ctx context.Context, workspaceID string) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ContainerName,
			&i.Port,
			&i.ServerID,
			&i.WorkspaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET name = $2, image = $3, container_name = $4, port = $5, server_id = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, name, image, container_name, port, server_id, workspace_id, created_at, updated_at
`

type UpdateApplicationParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Image         string `json:"image"`
	ContainerName string `json:"container_name"`
	Port          int32  `json:"port"`
	ServerID      string `json:"server_id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.ContainerName,
		arg.Port,
		arg.ServerID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.Port,
		&i.ServerID,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
