// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: application_domains.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPrimaryByApplication = `-- name: ClearPrimaryByApplication :exec
UPDATE application_domains
SET is_primary = FALSE, updated_at = NOW()
WHERE application_id = $1 AND is_primary = TRUE
`

func (q *Queries) ClearPrimaryByApplication(ctx context.Context, applicationID string) error {
	_, err := q.db.Exec(ctx, clearPrimaryByApplication, applicationID)
	return err
}

const createApplicationDomain = `-- name: CreateApplicationDomain :one
INSERT INTO application_domains (application_id, domain, is_primary)
VALUES ($1, $2, $3)
RETURNING id, application_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
`

type CreateApplicationDomainParams struct {
	ApplicationID string `json:"application_id"`
	Domain        string `json:"domain"`
	IsPrimary     bool   `json:"is_primary"`
}

func (q *Queries) CreateApplicationDomain(ctx context.Context, arg CreateApplicationDomainParams) (ApplicationDomain, error) {
	row := q.db.QueryRow(ctx, createApplicationDomain, arg.ApplicationID, arg.Domain, arg.IsPrimary)
	var i ApplicationDomain
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Domain,
		&i.IsPrimary,
		&i.Status,
		&i.LastError,
		&i.LastReconciledAt,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplicationDomain = `-- name: DeleteApplicationDomain :exec
DELETE FROM application_domains WHERE id = $1
`

func (q *Queries) DeleteApplicationDomain(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteApplicationDomain, id)
	return err
}

const getApplicationDomainByID = `-- name: GetApplicationDomainByID :one
SELECT id, application_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
FROM application_domains WHERE id = $1
`

func (q *Queries) GetApplicationDomainByID(ctx context.Context, id string) (ApplicationDomain, error) {
	row := q.db.QueryRow(ctx, getApplicationDomainByID, id)
	var i ApplicationDomain
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Domain,
		&i.IsPrimary,
		&i.Status,
		&i.LastError,
		&i.LastReconciledAt,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDomainsByApplication = `-- name: ListDomainsByApplication :many
SELECT id, application_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
FROM application_domains WHERE application_id = $1
ORDER BY is_primary DESC, created_at ASC
`

func (q *Queries) ListDomainsByApplication(ctx context.Context, applicationID string) ([]ApplicationDomain, error) {
	rows, err := q.db.Query(ctx, listDomainsByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationDomain{}
	for rows.Next() {
		var i ApplicationDomain
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Domain,
			&i.IsPrimary,
			&i.Status,
			&i.LastError,
			&i.LastReconciledAt,
			&i.ReadyAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedDomains = `-- name: ListUnresolvedDomains :many
SELECT d.id, d.domain, d.application_id,
       a.server_id,
       s.host, s.port AS server_port, s.ssh_user,
       k.private_key
FROM application_domains d
JOIN applications a ON a.id = d.application_id
JOIN servers s ON s.id = a.server_id
JOIN ssh_keys k ON k.id = s.ssh_key_id
WHERE d.status IN ('pending', 'error')
`

type ListUnresolvedDomainsRow struct {
	ID            string `json:"id"`
	Domain        string `json:"domain"`
	ApplicationID string `json:"application_id"`
	ServerID      string `json:"server_id"`
	Host          string `json:"host"`
	ServerPort    int32  `json:"server_port"`
	SshUser       string `json:"ssh_user"`
	PrivateKey    string `json:"private_key"`
}

func (q *Queries) ListUnresolvedDomains(ctx context.Context) ([]ListUnresolvedDomainsRow, error) {
	rows, err := q.db.Query(ctx, listUnresolvedDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnresolvedDomainsRow{}
	for rows.Next() {
		var i ListUnresolvedDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.ApplicationID,
			&i.ServerID,
			&i.Host,
			&i.ServerPort,
			&i.SshUser,
			&i.PrivateKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDomainError = `-- name: SetDomainError :exec
UPDATE application_domains
SET status = 'error', last_error = $2, last_reconciled_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type SetDomainErrorParams struct {
	ID        string      `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) SetDomainError(ctx context.Context, arg SetDomainErrorParams) error {
	_, err := q.db.Exec(ctx, setDomainError, arg.ID, arg.LastError)
	return err
}

const setDomainReady = `-- name: SetDomainReady :exec
UPDATE application_domains
SET status = 'ready', ready_at = NOW(), last_error = NULL, last_reconciled_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SetDomainReady(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setDomainReady, id)
	return err
}

const updateApplicationDomainPrimary = `-- name: UpdateApplicationDomainPrimary :one
UPDATE application_domains
SET is_primary = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, application_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
`

type UpdateApplicationDomainPrimaryParams struct {
	ID        string `json:"id"`
	IsPrimary bool   `json:"is_primary"`
}

func (q *Queries) UpdateApplicationDomainPrimary(ctx context.Context, arg UpdateApplicationDomainPrimaryParams) (ApplicationDomain, error) {
	row := q.db.QueryRow(ctx, updateApplicationDomainPrimary, arg.ID, arg.IsPrimary)
	var i ApplicationDomain
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Domain,
		&i.IsPrimary,
		&i.Status,
		&i.LastError,
		&i.LastReconciledAt,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
