// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: application_envs.sql

package sqlcgen

import (
	"context"
)

const deleteApplicationEnv = `-- name: DeleteApplicationEnv :exec
DELETE FROM application_envs
WHERE application_id = $1 AND key = $2
`

type DeleteApplicationEnvParams struct {
	ApplicationID string `json:"application_id"`
	Key           string `json:"key"`
}

func (q *Queries) DeleteApplicationEnv(ctx context.Context, arg DeleteApplicationEnvParams) error {
	_, err := q.db.Exec(ctx, deleteApplicationEnv, arg.ApplicationID, arg.Key)
	return err
}

const getApplicationEnvsByAppID = `-- name: GetApplicationEnvsByAppID :many
SELECT key, value FROM application_envs
WHERE application_id = $1
ORDER BY key ASC
`

type GetApplicationEnvsByAppIDRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetApplicationEnvsByAppID(ctx context.Context, applicationID string) ([]GetApplicationEnvsByAppIDRow, error) {
	rows, err := q.db.Query(ctx, getApplicationEnvsByAppID, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetApplicationEnvsByAppIDRow{}
	for rows.Next() {
		var i GetApplicationEnvsByAppIDRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationEnvs = `-- name: ListApplicationEnvs :many
SELECT id, application_id, key, value, created_at, updated_at FROM application_envs
WHERE application_id = $1
ORDER BY key ASC
`

func (q *Queries) ListApplicationEnvs(ctx context.Context, applicationID string) ([]ApplicationEnv, error) {
	rows, err := q.db.Query(ctx, listApplicationEnvs, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationEnv{}
	for rows.Next() {
		var i ApplicationEnv
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertApplicationEnv = `-- name: UpsertApplicationEnv :one
INSERT INTO application_envs (application_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (application_id, key)
DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
RETURNING id, application_id, key, value, created_at, updated_at
`

type UpsertApplicationEnvParams struct {
	ApplicationID string `json:"application_id"`
	Key           string `json:"key"`
	Value         string `json:"value"`
}

func (q *Queries) UpsertApplicationEnv(ctx context.Context, arg UpsertApplicationEnvParams) (ApplicationEnv, error) {
	row := q.db.QueryRow(ctx, upsertApplicationEnv, arg.ApplicationID, arg.Key, arg.Value)
	var i ApplicationEnv
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
