// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (status, workspace_id) VALUES ('in_progress', $1)
RETURNING id, status, workspace_id
`

func (q *Queries) CreateDeployment(ctx context.Context, workspaceID pgtype.Text) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment, workspaceID)
	var i Deployment
	err := row.Scan(&i.ID, &i.Status, &i.WorkspaceID)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, status, workspace_id FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(&i.ID, &i.Status, &i.WorkspaceID)
	return i, err
}

const setDeploymentStatus = `-- name: SetDeploymentStatus :exec
UPDATE deployments SET status = $1 WHERE id = $2
`

type SetDeploymentStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) SetDeploymentStatus(ctx context.Context, arg SetDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, setDeploymentStatus, arg.Status, arg.ID)
	return err
}
