// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_logs.sql

package sqlcgen

import (
	"context"
	"time"
)

const getLogsAfter = `-- name: GetLogsAfter :many
SELECT id, "order", created_at, output, type, phase
FROM deployment_logs
WHERE deployment_id = $1 AND "order" > $2
ORDER BY "order" ASC
`

type GetLogsAfterParams struct {
	DeploymentID string `json:"deployment_id"`
	Order        int32  `json:"order"`
}

type GetLogsAfterRow struct {
	ID        int64     `json:"id"`
	Order     int32     `json:"order"`
	CreatedAt time.Time `json:"created_at"`
	Output    string    `json:"output"`
	Type      string    `json:"type"`
	Phase     string    `json:"phase"`
}

func (q *Queries) GetLogsAfter(ctx context.Context, arg GetLogsAfterParams) ([]GetLogsAfterRow, error) {
	rows, err := q.db.Query(ctx, getLogsAfter, arg.DeploymentID, arg.Order)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLogsAfterRow{}
	for rows.Next() {
		var i GetLogsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Order,
			&i.CreatedAt,
			&i.Output,
			&i.Type,
			&i.Phase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDeploymentLog = `-- name: InsertDeploymentLog :one
INSERT INTO deployment_logs (deployment_id, "order", output, type, phase)
VALUES ($1, (SELECT COALESCE(MAX("order"), 0) + 1 FROM deployment_logs WHERE deployment_id = $1), $2, $3, $4)
RETURNING id, "order", created_at
`

type InsertDeploymentLogParams struct {
	DeploymentID string `json:"deployment_id"`
	Output       string `json:"output"`
	Type         string `json:"type"`
	Phase        string `json:"phase"`
}

type InsertDeploymentLogRow struct {
	ID        int64     `json:"id"`
	Order     int32     `json:"order"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertDeploymentLog(ctx context.Context, arg InsertDeploymentLogParams) (InsertDeploymentLogRow, error) {
	row := q.db.QueryRow(ctx, insertDeploymentLog,
		arg.DeploymentID,
		arg.Output,
		arg.Type,
		arg.Phase,
	)
	var i InsertDeploymentLogRow
	err := row.Scan(&i.ID, &i.Order, &i.CreatedAt)
	return i, err
}
