// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (status, workspace_id, service_id, configuration_snapshot)
VALUES ('in_progress', $1, $2, $3)
RETURNING id, status, workspace_id, service_id, created_at
`

type CreateDeploymentParams struct {
	WorkspaceID           pgtype.Text `json:"workspace_id"`
	ServiceID             string      `json:"service_id"`
	ConfigurationSnapshot pgtype.Text `json:"configuration_snapshot"`
}

type CreateDeploymentRow struct {
	ID          string      `json:"id"`
	Status      string      `json:"status"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
	ServiceID   string      `json:"service_id"`
	CreatedAt   time.Time   `json:"created_at"`
}

// The snapshot is written here, at creation, from the same config object the
// job is about to render into a `docker run` — not read back from the database
// when the deploy finishes. A deploy takes tens of seconds, and an edit landing
// during one would otherwise be recorded as deployed without ever reaching the
// server, which is exactly the lie this column exists to prevent.
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (CreateDeploymentRow, error) {
	row := q.db.QueryRow(ctx, createDeployment, arg.WorkspaceID, arg.ServiceID, arg.ConfigurationSnapshot)
	var i CreateDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.WorkspaceID,
		&i.ServiceID,
		&i.CreatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, status, workspace_id, service_id, created_at
FROM deployments WHERE id = $1
`

type GetDeploymentRow struct {
	ID          string      `json:"id"`
	Status      string      `json:"status"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
	ServiceID   string      `json:"service_id"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) GetDeployment(ctx context.Context, id string) (GetDeploymentRow, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i GetDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.WorkspaceID,
		&i.ServiceID,
		&i.CreatedAt,
	)
	return i, err
}

const getDeploymentConfig = `-- name: GetDeploymentConfig :one
SELECT configuration_snapshot
FROM deployments
WHERE id = $1
`

func (q *Queries) GetDeploymentConfig(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getDeploymentConfig, id)
	var configuration_snapshot pgtype.Text
	err := row.Scan(&configuration_snapshot)
	return configuration_snapshot, err
}

const getLatestDeploymentPhase = `-- name: GetLatestDeploymentPhase :one
SELECT COALESCE((
    SELECT phase
    FROM deployment_logs
    WHERE deployment_id = $1
      AND phase <> 'recovery_pending'
    ORDER BY "order" DESC
    LIMIT 1
), '')::text AS phase
`

func (q *Queries) GetLatestDeploymentPhase(ctx context.Context, deploymentID string) (string, error) {
	row := q.db.QueryRow(ctx, getLatestDeploymentPhase, deploymentID)
	var phase string
	err := row.Scan(&phase)
	return phase, err
}

const getLatestSuccessfulDeploymentConfig = `-- name: GetLatestSuccessfulDeploymentConfig :one
SELECT id, configuration_snapshot
FROM deployments
WHERE service_id = $1
  AND status = 'success'
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestSuccessfulDeploymentConfigRow struct {
	ID                    string      `json:"id"`
	ConfigurationSnapshot pgtype.Text `json:"configuration_snapshot"`
}

func (q *Queries) GetLatestSuccessfulDeploymentConfig(ctx context.Context, serviceID string) (GetLatestSuccessfulDeploymentConfigRow, error) {
	row := q.db.QueryRow(ctx, getLatestSuccessfulDeploymentConfig, serviceID)
	var i GetLatestSuccessfulDeploymentConfigRow
	err := row.Scan(&i.ID, &i.ConfigurationSnapshot)
	return i, err
}

const listDeploymentsByService = `-- name: ListDeploymentsByService :many
WITH service_deployments AS (
    SELECT d.id, d.status, d.workspace_id, d.service_id, d.created_at, d.configuration_snapshot,
           COALESCE((
               SELECT phase
               FROM deployment_logs l
               WHERE l.deployment_id = d.id
                 AND l.phase <> 'recovery_pending'
               ORDER BY l."order" DESC
               LIMIT 1
           ), '') AS phase,
           COALESCE((
               SELECT MIN(l.created_at)
               FROM deployment_logs l
               WHERE l.deployment_id = d.id
           ), d.created_at) AS started_at,
           COALESCE((
               SELECT MAX(l.created_at)::timestamptz
               FROM deployment_logs l
               WHERE l.deployment_id = d.id
           ), d.created_at) AS completed_at
    FROM deployments d
    WHERE d.service_id = $1
), current_deployment AS (
    SELECT id, status, phase
    FROM service_deployments
    ORDER BY created_at DESC
    LIMIT 1
), latest_success AS (
    SELECT id
    FROM service_deployments
    WHERE status = 'success'
    ORDER BY created_at DESC
    LIMIT 1
)
, marked AS (
SELECT d.id,
       d.status::text AS status,
       d.workspace_id,
       d.service_id,
       d.created_at,
       d.configuration_snapshot,
       d.phase::text AS phase,
       d.started_at,
       d.completed_at,
       COALESCE((CASE
           WHEN current_deployment.status = 'in_progress' AND current_deployment.phase IN ('active', 'drain')
               THEN d.id = current_deployment.id
           ELSE d.id = latest_success.id
       END), false)::boolean AS is_active,
       COALESCE(
           current_deployment.status = 'in_progress'
           AND current_deployment.phase = 'drain'
           AND d.id = latest_success.id,
           false
       )::boolean AS is_draining
FROM service_deployments d
LEFT JOIN current_deployment ON true
LEFT JOIN latest_success ON true
)
SELECT id, status, workspace_id, service_id, created_at, configuration_snapshot, phase, started_at, completed_at, is_active, is_draining
FROM marked
WHERE id IN (SELECT id FROM marked ORDER BY created_at DESC LIMIT $2)
   OR is_active
   OR is_draining
ORDER BY created_at DESC
`

type ListDeploymentsByServiceParams struct {
	ServiceID string `json:"service_id"`
	Limit     int32  `json:"limit"`
}

type ListDeploymentsByServiceRow struct {
	ID                    string      `json:"id"`
	Status                string      `json:"status"`
	WorkspaceID           pgtype.Text `json:"workspace_id"`
	ServiceID             string      `json:"service_id"`
	CreatedAt             time.Time   `json:"created_at"`
	ConfigurationSnapshot pgtype.Text `json:"configuration_snapshot"`
	Phase                 string      `json:"phase"`
	StartedAt             time.Time   `json:"started_at"`
	CompletedAt           time.Time   `json:"completed_at"`
	IsActive              bool        `json:"is_active"`
	IsDraining            bool        `json:"is_draining"`
}

func (q *Queries) ListDeploymentsByService(ctx context.Context, arg ListDeploymentsByServiceParams) ([]ListDeploymentsByServiceRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByService, arg.ServiceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentsByServiceRow{}
	for rows.Next() {
		var i ListDeploymentsByServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.WorkspaceID,
			&i.ServiceID,
			&i.CreatedAt,
			&i.ConfigurationSnapshot,
			&i.Phase,
			&i.StartedAt,
			&i.CompletedAt,
			&i.IsActive,
			&i.IsDraining,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInProgressDeploymentIDs = `-- name: ListInProgressDeploymentIDs :many
SELECT id
FROM deployments
WHERE status = 'in_progress'
ORDER BY created_at ASC
`

func (q *Queries) ListInProgressDeploymentIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listInProgressDeploymentIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestSuccessfulConfigs = `-- name: ListLatestSuccessfulConfigs :many
SELECT DISTINCT ON (service_id) service_id, configuration_snapshot
FROM deployments
WHERE service_id = ANY($1::text[])
  AND status = 'success'
  AND configuration_snapshot IS NOT NULL
ORDER BY service_id, created_at DESC
`

type ListLatestSuccessfulConfigsRow struct {
	ServiceID             string      `json:"service_id"`
	ConfigurationSnapshot pgtype.Text `json:"configuration_snapshot"`
}

// The config each service is actually running: its most recent successful
// deployment's snapshot. One row per service, so a canvas full of them costs one
// query rather than one each.
//
// Failed deployments are excluded because they changed nothing on the server,
// and null snapshots because they predate the column and describe nothing.
func (q *Queries) ListLatestSuccessfulConfigs(ctx context.Context, serviceIds []string) ([]ListLatestSuccessfulConfigsRow, error) {
	rows, err := q.db.Query(ctx, listLatestSuccessfulConfigs, serviceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestSuccessfulConfigsRow{}
	for rows.Next() {
		var i ListLatestSuccessfulConfigsRow
		if err := rows.Scan(&i.ServiceID, &i.ConfigurationSnapshot); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceHasInProgressDeployment = `-- name: ServiceHasInProgressDeployment :one
SELECT EXISTS (
    SELECT 1 FROM deployments WHERE service_id = $1 AND status = 'in_progress'
)
`

func (q *Queries) ServiceHasInProgressDeployment(ctx context.Context, serviceID string) (bool, error) {
	row := q.db.QueryRow(ctx, serviceHasInProgressDeployment, serviceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setDeploymentStatus = `-- name: SetDeploymentStatus :exec
UPDATE deployments SET status = $1 WHERE id = $2
`

type SetDeploymentStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) SetDeploymentStatus(ctx context.Context, arg SetDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, setDeploymentStatus, arg.Status, arg.ID)
	return err
}
