// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package sqlcgen

import (
	"context"
	"time"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO workspace_memberships (workspace_id, user_id, role) VALUES ($1, $2, $3)
RETURNING id, workspace_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	Role        string `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, workspace_id, user_id, role, created_at
FROM workspace_memberships WHERE workspace_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (WorkspaceMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMembership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserFirstWorkspace = `-- name: GetUserFirstWorkspace :one
SELECT
    w.id AS w_id, w.name AS w_name, w.owner_user_id AS w_owner_user_id,
    w.created_at AS w_created_at, w.updated_at AS w_updated_at,
    wm.id AS wm_id, wm.workspace_id AS wm_workspace_id, wm.user_id AS wm_user_id,
    wm.role AS wm_role, wm.created_at AS wm_created_at
FROM workspace_memberships wm
JOIN workspaces w ON w.id = wm.workspace_id
WHERE wm.user_id = $1
ORDER BY wm.created_at ASC
LIMIT 1
`

type GetUserFirstWorkspaceRow struct {
	WID           string    `json:"w_id"`
	WName         string    `json:"w_name"`
	WOwnerUserID  string    `json:"w_owner_user_id"`
	WCreatedAt    time.Time `json:"w_created_at"`
	WUpdatedAt    time.Time `json:"w_updated_at"`
	WmID          string    `json:"wm_id"`
	WmWorkspaceID string    `json:"wm_workspace_id"`
	WmUserID      string    `json:"wm_user_id"`
	WmRole        string    `json:"wm_role"`
	WmCreatedAt   time.Time `json:"wm_created_at"`
}

func (q *Queries) GetUserFirstWorkspace(ctx context.Context, userID string) (GetUserFirstWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getUserFirstWorkspace, userID)
	var i GetUserFirstWorkspaceRow
	err := row.Scan(
		&i.WID,
		&i.WName,
		&i.WOwnerUserID,
		&i.WCreatedAt,
		&i.WUpdatedAt,
		&i.WmID,
		&i.WmWorkspaceID,
		&i.WmUserID,
		&i.WmRole,
		&i.WmCreatedAt,
	)
	return i, err
}
