// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Deployment struct {
	ID          string      `json:"id"`
	Status      string      `json:"status"`
	WorkspaceID pgtype.Text `json:"workspace_id"`
	ServiceID   string      `json:"service_id"`
	CreatedAt   time.Time   `json:"created_at"`
}

type DeploymentLog struct {
	ID           int64     `json:"id"`
	DeploymentID string    `json:"deployment_id"`
	Output       string    `json:"output"`
	CreatedAt    time.Time `json:"created_at"`
	Order        int32     `json:"order"`
	Type         string    `json:"type"`
	Phase        string    `json:"phase"`
}

type Environment struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	ProjectID string    `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type OauthIdentity struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	ProviderEmail  string    `json:"provider_email"`
	CreatedAt      time.Time `json:"created_at"`
}

type Project struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	WorkspaceID string    `json:"workspace_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Server struct {
	ID                    string             `json:"id"`
	Name                  string             `json:"name"`
	Host                  string             `json:"host"`
	Port                  int32              `json:"port"`
	SshUser               string             `json:"ssh_user"`
	SshKeyID              string             `json:"ssh_key_id"`
	WorkspaceID           string             `json:"workspace_id"`
	CreatedAt             time.Time          `json:"created_at"`
	ProxyStatus           string             `json:"proxy_status"`
	ProxyLastReconciledAt pgtype.Timestamptz `json:"proxy_last_reconciled_at"`
	ProxyLastError        pgtype.Text        `json:"proxy_last_error"`
}

type Service struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Image         string    `json:"image"`
	ContainerName string    `json:"container_name"`
	Port          int32     `json:"port"`
	ServerID      string    `json:"server_id"`
	WorkspaceID   string    `json:"workspace_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Kind          string    `json:"kind"`
	ProjectID     string    `json:"project_id"`
	EnvironmentID string    `json:"environment_id"`
}

type ServiceDomain struct {
	ID               string             `json:"id"`
	ServiceID        string             `json:"service_id"`
	Domain           string             `json:"domain"`
	IsPrimary        bool               `json:"is_primary"`
	Status           string             `json:"status"`
	LastError        pgtype.Text        `json:"last_error"`
	LastReconciledAt pgtype.Timestamptz `json:"last_reconciled_at"`
	ReadyAt          pgtype.Timestamptz `json:"ready_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type ServiceEnvVar struct {
	ID        int64     `json:"id"`
	ServiceID string    `json:"service_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Session struct {
	Token       string    `json:"token"`
	UserID      string    `json:"user_id"`
	WorkspaceID string    `json:"workspace_id"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type SshKey struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	PrivateKey  string    `json:"private_key"`
	WorkspaceID string    `json:"workspace_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	PlatformRole string    `json:"platform_role"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Workspace struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	OwnerUserID string    `json:"owner_user_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type WorkspaceMembership struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	UserID      string    `json:"user_id"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}
