// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AlertEvent struct {
	ID            string             `json:"id"`
	WorkspaceID   string             `json:"workspace_id"`
	RuleID        string             `json:"rule_id"`
	TargetID      string             `json:"target_id"`
	TargetName    string             `json:"target_name"`
	Status        string             `json:"status"`
	StartedAt     time.Time          `json:"started_at"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
	TriggerValue  float64            `json:"trigger_value"`
	ResolvedValue pgtype.Float8      `json:"resolved_value"`
	CreatedAt     time.Time          `json:"created_at"`
}

type AlertRule struct {
	ID              string      `json:"id"`
	WorkspaceID     string      `json:"workspace_id"`
	Name            string      `json:"name"`
	Condition       string      `json:"condition"`
	Threshold       float64     `json:"threshold"`
	DurationSeconds int32       `json:"duration_seconds"`
	ScopeType       string      `json:"scope_type"`
	ServerID        pgtype.Text `json:"server_id"`
	ServiceID       pgtype.Text `json:"service_id"`
	Enabled         bool        `json:"enabled"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type AlertRuleChannel struct {
	RuleID    string `json:"rule_id"`
	ChannelID string `json:"channel_id"`
}

type Deployment struct {
	ID                    string      `json:"id"`
	Status                string      `json:"status"`
	WorkspaceID           pgtype.Text `json:"workspace_id"`
	ServiceID             string      `json:"service_id"`
	CreatedAt             time.Time   `json:"created_at"`
	ConfigurationSnapshot pgtype.Text `json:"configuration_snapshot"`
}

type DeploymentLog struct {
	ID           int64     `json:"id"`
	DeploymentID string    `json:"deployment_id"`
	Output       string    `json:"output"`
	CreatedAt    time.Time `json:"created_at"`
	Order        int32     `json:"order"`
	Type         string    `json:"type"`
	Phase        string    `json:"phase"`
}

type Environment struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	ProjectID string    `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type NotificationChannel struct {
	ID               string    `json:"id"`
	WorkspaceID      string    `json:"workspace_id"`
	Name             string    `json:"name"`
	Type             string    `json:"type"`
	ConfigCiphertext string    `json:"config_ciphertext"`
	Enabled          bool      `json:"enabled"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type OauthIdentity struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	ProviderEmail  string    `json:"provider_email"`
	CreatedAt      time.Time `json:"created_at"`
}

type Project struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	WorkspaceID string    `json:"workspace_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Server struct {
	ID                         string             `json:"id"`
	Name                       string             `json:"name"`
	Host                       string             `json:"host"`
	Port                       int32              `json:"port"`
	SshUser                    string             `json:"ssh_user"`
	SshKeyID                   string             `json:"ssh_key_id"`
	WorkspaceID                string             `json:"workspace_id"`
	CreatedAt                  time.Time          `json:"created_at"`
	ProxyStatus                string             `json:"proxy_status"`
	ProxyLastReconciledAt      pgtype.Timestamptz `json:"proxy_last_reconciled_at"`
	ProxyLastError             pgtype.Text        `json:"proxy_last_error"`
	MonitoringEnabled          bool               `json:"monitoring_enabled"`
	MonitoringPort             int32              `json:"monitoring_port"`
	MonitoringRetentionDays    int32              `json:"monitoring_retention_days"`
	MonitoringPrivateAddress   string             `json:"monitoring_private_address"`
	MonitoringFqdn             pgtype.Text        `json:"monitoring_fqdn"`
	MonitoringControlToken     pgtype.Text        `json:"monitoring_control_token"`
	MonitoringReaderToken      pgtype.Text        `json:"monitoring_reader_token"`
	MonitoringStatus           string             `json:"monitoring_status"`
	MonitoringLastReconciledAt pgtype.Timestamptz `json:"monitoring_last_reconciled_at"`
	MonitoringLastError        pgtype.Text        `json:"monitoring_last_error"`
	MonitoringCleanupAt        pgtype.Timestamptz `json:"monitoring_cleanup_at"`
}

type Service struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	ServerID      string      `json:"server_id"`
	WorkspaceID   string      `json:"workspace_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	Kind          string      `json:"kind"`
	ProjectID     string      `json:"project_id"`
	EnvironmentID string      `json:"environment_id"`
	HostPort      pgtype.Int4 `json:"host_port"`
}

type ServiceDomain struct {
	ID               string             `json:"id"`
	ServiceID        string             `json:"service_id"`
	Domain           string             `json:"domain"`
	IsPrimary        bool               `json:"is_primary"`
	Status           string             `json:"status"`
	LastError        pgtype.Text        `json:"last_error"`
	LastReconciledAt pgtype.Timestamptz `json:"last_reconciled_at"`
	ReadyAt          pgtype.Timestamptz `json:"ready_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type ServiceEnvVar struct {
	ID        int64     `json:"id"`
	ServiceID string    `json:"service_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Session struct {
	Token       string    `json:"token"`
	UserID      string    `json:"user_id"`
	WorkspaceID string    `json:"workspace_id"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type SshKey struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	PrivateKey  string    `json:"private_key"`
	WorkspaceID string    `json:"workspace_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	PlatformRole string    `json:"platform_role"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Workspace struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	OwnerUserID string    `json:"owner_user_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type WorkspaceMembership struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	UserID      string    `json:"user_id"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}
