// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_identities.sql

package sqlcgen

import (
	"context"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (user_id, provider, provider_user_id, provider_email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, provider_user_id, provider_email, created_at
`

type CreateOAuthIdentityParams struct {
	UserID         string `json:"user_id"`
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
	ProviderEmail  string `json:"provider_email"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderEmail,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthIdentitiesByUser = `-- name: GetOAuthIdentitiesByUser :many
SELECT id, user_id, provider, provider_user_id, provider_email, created_at
FROM oauth_identities WHERE user_id = $1
`

func (q *Queries) GetOAuthIdentitiesByUser(ctx context.Context, userID string) ([]OauthIdentity, error) {
	rows, err := q.db.Query(ctx, getOAuthIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthIdentity{}
	for rows.Next() {
		var i OauthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.ProviderEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT id, user_id, provider, provider_user_id, provider_email, created_at
FROM oauth_identities WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthIdentityParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.CreatedAt,
	)
	return i, err
}
