// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_sources.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceSource = `-- name: CreateServiceSource :one
INSERT INTO service_sources (service_id, provider, owner, repo, branch, root_dir, detected)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING service_id, provider, owner, repo, branch, root_dir, detected, created_at, updated_at
`

type CreateServiceSourceParams struct {
	ServiceID string      `json:"service_id"`
	Provider  string      `json:"provider"`
	Owner     string      `json:"owner"`
	Repo      string      `json:"repo"`
	Branch    string      `json:"branch"`
	RootDir   pgtype.Text `json:"root_dir"`
	Detected  []byte      `json:"detected"`
}

func (q *Queries) CreateServiceSource(ctx context.Context, arg CreateServiceSourceParams) (ServiceSource, error) {
	row := q.db.QueryRow(ctx, createServiceSource,
		arg.ServiceID,
		arg.Provider,
		arg.Owner,
		arg.Repo,
		arg.Branch,
		arg.RootDir,
		arg.Detected,
	)
	var i ServiceSource
	err := row.Scan(
		&i.ServiceID,
		&i.Provider,
		&i.Owner,
		&i.Repo,
		&i.Branch,
		&i.RootDir,
		&i.Detected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceSourceByServiceID = `-- name: GetServiceSourceByServiceID :one
SELECT service_id, provider, owner, repo, branch, root_dir, detected, created_at, updated_at
FROM service_sources
WHERE service_id = $1
`

func (q *Queries) GetServiceSourceByServiceID(ctx context.Context, serviceID string) (ServiceSource, error) {
	row := q.db.QueryRow(ctx, getServiceSourceByServiceID, serviceID)
	var i ServiceSource
	err := row.Scan(
		&i.ServiceID,
		&i.Provider,
		&i.Owner,
		&i.Repo,
		&i.Branch,
		&i.RootDir,
		&i.Detected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceSourcesByServiceIDs = `-- name: ListServiceSourcesByServiceIDs :many
SELECT service_id, provider, owner, repo, branch, root_dir, detected, created_at, updated_at
FROM service_sources
WHERE service_id = ANY($1::text[])
ORDER BY service_id
`

func (q *Queries) ListServiceSourcesByServiceIDs(ctx context.Context, serviceIds []string) ([]ServiceSource, error) {
	rows, err := q.db.Query(ctx, listServiceSourcesByServiceIDs, serviceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceSource{}
	for rows.Next() {
		var i ServiceSource
		if err := rows.Scan(
			&i.ServiceID,
			&i.Provider,
			&i.Owner,
			&i.Repo,
			&i.Branch,
			&i.RootDir,
			&i.Detected,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
