// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_domains.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPrimaryByService = `-- name: ClearPrimaryByService :exec
UPDATE service_domains
SET is_primary = FALSE, updated_at = NOW()
WHERE service_id = $1 AND is_primary = TRUE
`

func (q *Queries) ClearPrimaryByService(ctx context.Context, serviceID string) error {
	_, err := q.db.Exec(ctx, clearPrimaryByService, serviceID)
	return err
}

const createServiceDomain = `-- name: CreateServiceDomain :one
INSERT INTO service_domains (service_id, domain, is_primary)
VALUES ($1, $2, $3)
RETURNING id, service_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
`

type CreateServiceDomainParams struct {
	ServiceID string `json:"service_id"`
	Domain    string `json:"domain"`
	IsPrimary bool   `json:"is_primary"`
}

func (q *Queries) CreateServiceDomain(ctx context.Context, arg CreateServiceDomainParams) (ServiceDomain, error) {
	row := q.db.QueryRow(ctx, createServiceDomain, arg.ServiceID, arg.Domain, arg.IsPrimary)
	var i ServiceDomain
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Domain,
		&i.IsPrimary,
		&i.Status,
		&i.LastError,
		&i.LastReconciledAt,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceDomain = `-- name: DeleteServiceDomain :exec
DELETE FROM service_domains WHERE id = $1
`

func (q *Queries) DeleteServiceDomain(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteServiceDomain, id)
	return err
}

const getServiceDomainByID = `-- name: GetServiceDomainByID :one
SELECT id, service_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
FROM service_domains WHERE id = $1
`

func (q *Queries) GetServiceDomainByID(ctx context.Context, id string) (ServiceDomain, error) {
	row := q.db.QueryRow(ctx, getServiceDomainByID, id)
	var i ServiceDomain
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Domain,
		&i.IsPrimary,
		&i.Status,
		&i.LastError,
		&i.LastReconciledAt,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDomainNamesByServiceIDs = `-- name: ListDomainNamesByServiceIDs :many
SELECT service_id, domain FROM service_domains
WHERE service_id = ANY($1::text[])
ORDER BY service_id, domain ASC
`

type ListDomainNamesByServiceIDsRow struct {
	ServiceID string `json:"service_id"`
	Domain    string `json:"domain"`
}

// Just the hostnames, for a whole set of services at once — what a deploy puts
// in the container's Traefik rule, and so what a config snapshot holds. Sorted
// within each service for the same reason the env vars are: the config is
// compared as a document, and reordering must not read as a change.
func (q *Queries) ListDomainNamesByServiceIDs(ctx context.Context, serviceIds []string) ([]ListDomainNamesByServiceIDsRow, error) {
	rows, err := q.db.Query(ctx, listDomainNamesByServiceIDs, serviceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainNamesByServiceIDsRow{}
	for rows.Next() {
		var i ListDomainNamesByServiceIDsRow
		if err := rows.Scan(&i.ServiceID, &i.Domain); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsByService = `-- name: ListDomainsByService :many
SELECT id, service_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
FROM service_domains WHERE service_id = $1
ORDER BY is_primary DESC, created_at ASC
`

func (q *Queries) ListDomainsByService(ctx context.Context, serviceID string) ([]ServiceDomain, error) {
	rows, err := q.db.Query(ctx, listDomainsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceDomain{}
	for rows.Next() {
		var i ServiceDomain
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Domain,
			&i.IsPrimary,
			&i.Status,
			&i.LastError,
			&i.LastReconciledAt,
			&i.ReadyAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsToReconcile = `-- name: ListDomainsToReconcile :many
SELECT d.id, d.domain, d.status, d.service_id,
       s.server_id,
       srv.host, srv.port AS server_port, srv.ssh_user,
       k.private_key
FROM service_domains d
JOIN services s ON s.id = d.service_id
JOIN servers srv ON srv.id = s.server_id
JOIN ssh_keys k ON k.id = srv.ssh_key_id
WHERE d.status IN ('pending', 'error', 'ready')
  AND EXISTS (
    SELECT 1 FROM deployments dep
    WHERE dep.service_id = d.service_id
      AND dep.status = 'success'
      AND dep.created_at > d.created_at
  )
`

type ListDomainsToReconcileRow struct {
	ID         string `json:"id"`
	Domain     string `json:"domain"`
	Status     string `json:"status"`
	ServiceID  string `json:"service_id"`
	ServerID   string `json:"server_id"`
	Host       string `json:"host"`
	ServerPort int32  `json:"server_port"`
	SshUser    string `json:"ssh_user"`
	PrivateKey string `json:"private_key"`
}

// The domains worth checking, ready ones included.
//
// Readiness is read off acme.json, which is Traefik's store for the whole
// server and is never pruned: a hostname that got a certificate once stays
// spelled out in that file after the domain is removed, after the service is
// redeployed without it, forever. Grepping it alone therefore answers "did this
// name ever have a certificate here", not "is this service serving it now" —
// and a domain added back later was promoted the next minute while no container
// carried a matching Traefik rule at all.
//
// The deploy requirement is what closes that: the Host() rule is only written
// during a deploy, so a certificate can only belong to this domain if a
// successful deploy happened after the domain row existed. An older one issued
// the stale entry and does not count.
//
// Ready domains are here too, which is why this is no longer "unresolved". A
// certificate proves the name worked once; nothing about it expires when the DNS
// record is deleted, so a domain that stopped resolving would otherwise keep
// claiming HTTPS forever. Re-checking is what lets one fall back to pending, and
// the DNS half of the check costs no SSH, so a pass over settled domains is
// nearly free.
func (q *Queries) ListDomainsToReconcile(ctx context.Context) ([]ListDomainsToReconcileRow, error) {
	rows, err := q.db.Query(ctx, listDomainsToReconcile)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainsToReconcileRow{}
	for rows.Next() {
		var i ListDomainsToReconcileRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Status,
			&i.ServiceID,
			&i.ServerID,
			&i.Host,
			&i.ServerPort,
			&i.SshUser,
			&i.PrivateKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDomainError = `-- name: SetDomainError :exec
UPDATE service_domains
SET status = 'error', last_error = $2, last_reconciled_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type SetDomainErrorParams struct {
	ID        string      `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) SetDomainError(ctx context.Context, arg SetDomainErrorParams) error {
	_, err := q.db.Exec(ctx, setDomainError, arg.ID, arg.LastError)
	return err
}

const setDomainPending = `-- name: SetDomainPending :exec
UPDATE service_domains
SET status = 'pending', last_error = NULL, last_reconciled_at = NOW(), updated_at = NOW()
WHERE id = $1
`

// Puts a domain back to waiting, keeping ready_at as the record that it did work
// once. Used when a domain that had a certificate stops resolving to this server
// — the certificate is still on disk and still proves nothing about now.
func (q *Queries) SetDomainPending(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setDomainPending, id)
	return err
}

const setDomainReady = `-- name: SetDomainReady :exec
UPDATE service_domains
SET status = 'ready', ready_at = NOW(), last_error = NULL, last_reconciled_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SetDomainReady(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setDomainReady, id)
	return err
}

const touchDomainChecked = `-- name: TouchDomainChecked :exec
UPDATE service_domains
SET last_reconciled_at = NOW(), updated_at = NOW()
WHERE id = $1
`

// Records that a domain was looked at and nothing changed, so the panel can say
// when the answer was last confirmed rather than only when it last moved.
func (q *Queries) TouchDomainChecked(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchDomainChecked, id)
	return err
}

const updateServiceDomainPrimary = `-- name: UpdateServiceDomainPrimary :one
UPDATE service_domains
SET is_primary = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, service_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
`

type UpdateServiceDomainPrimaryParams struct {
	ID        string `json:"id"`
	IsPrimary bool   `json:"is_primary"`
}

func (q *Queries) UpdateServiceDomainPrimary(ctx context.Context, arg UpdateServiceDomainPrimaryParams) (ServiceDomain, error) {
	row := q.db.QueryRow(ctx, updateServiceDomainPrimary, arg.ID, arg.IsPrimary)
	var i ServiceDomain
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Domain,
		&i.IsPrimary,
		&i.Status,
		&i.LastError,
		&i.LastReconciledAt,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
