// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_domains.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPrimaryByService = `-- name: ClearPrimaryByService :exec
UPDATE service_domains
SET is_primary = FALSE, updated_at = NOW()
WHERE service_id = $1 AND is_primary = TRUE
`

func (q *Queries) ClearPrimaryByService(ctx context.Context, serviceID string) error {
	_, err := q.db.Exec(ctx, clearPrimaryByService, serviceID)
	return err
}

const createServiceDomain = `-- name: CreateServiceDomain :one
INSERT INTO service_domains (service_id, domain, is_primary)
VALUES ($1, $2, $3)
RETURNING id, service_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
`

type CreateServiceDomainParams struct {
	ServiceID string `json:"service_id"`
	Domain    string `json:"domain"`
	IsPrimary bool   `json:"is_primary"`
}

func (q *Queries) CreateServiceDomain(ctx context.Context, arg CreateServiceDomainParams) (ServiceDomain, error) {
	row := q.db.QueryRow(ctx, createServiceDomain, arg.ServiceID, arg.Domain, arg.IsPrimary)
	var i ServiceDomain
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Domain,
		&i.IsPrimary,
		&i.Status,
		&i.LastError,
		&i.LastReconciledAt,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceDomain = `-- name: DeleteServiceDomain :exec
DELETE FROM service_domains WHERE id = $1
`

func (q *Queries) DeleteServiceDomain(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteServiceDomain, id)
	return err
}

const getServiceDomainByID = `-- name: GetServiceDomainByID :one
SELECT id, service_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
FROM service_domains WHERE id = $1
`

func (q *Queries) GetServiceDomainByID(ctx context.Context, id string) (ServiceDomain, error) {
	row := q.db.QueryRow(ctx, getServiceDomainByID, id)
	var i ServiceDomain
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Domain,
		&i.IsPrimary,
		&i.Status,
		&i.LastError,
		&i.LastReconciledAt,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDomainsByService = `-- name: ListDomainsByService :many
SELECT id, service_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
FROM service_domains WHERE service_id = $1
ORDER BY is_primary DESC, created_at ASC
`

func (q *Queries) ListDomainsByService(ctx context.Context, serviceID string) ([]ServiceDomain, error) {
	rows, err := q.db.Query(ctx, listDomainsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceDomain{}
	for rows.Next() {
		var i ServiceDomain
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Domain,
			&i.IsPrimary,
			&i.Status,
			&i.LastError,
			&i.LastReconciledAt,
			&i.ReadyAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedDomains = `-- name: ListUnresolvedDomains :many
SELECT d.id, d.domain, d.service_id,
       s.server_id,
       srv.host, srv.port AS server_port, srv.ssh_user,
       k.private_key
FROM service_domains d
JOIN services s ON s.id = d.service_id
JOIN servers srv ON srv.id = s.server_id
JOIN ssh_keys k ON k.id = srv.ssh_key_id
WHERE d.status IN ('pending', 'error')
`

type ListUnresolvedDomainsRow struct {
	ID         string `json:"id"`
	Domain     string `json:"domain"`
	ServiceID  string `json:"service_id"`
	ServerID   string `json:"server_id"`
	Host       string `json:"host"`
	ServerPort int32  `json:"server_port"`
	SshUser    string `json:"ssh_user"`
	PrivateKey string `json:"private_key"`
}

func (q *Queries) ListUnresolvedDomains(ctx context.Context) ([]ListUnresolvedDomainsRow, error) {
	rows, err := q.db.Query(ctx, listUnresolvedDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnresolvedDomainsRow{}
	for rows.Next() {
		var i ListUnresolvedDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.ServiceID,
			&i.ServerID,
			&i.Host,
			&i.ServerPort,
			&i.SshUser,
			&i.PrivateKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDomainError = `-- name: SetDomainError :exec
UPDATE service_domains
SET status = 'error', last_error = $2, last_reconciled_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type SetDomainErrorParams struct {
	ID        string      `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) SetDomainError(ctx context.Context, arg SetDomainErrorParams) error {
	_, err := q.db.Exec(ctx, setDomainError, arg.ID, arg.LastError)
	return err
}

const setDomainReady = `-- name: SetDomainReady :exec
UPDATE service_domains
SET status = 'ready', ready_at = NOW(), last_error = NULL, last_reconciled_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SetDomainReady(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setDomainReady, id)
	return err
}

const updateServiceDomainPrimary = `-- name: UpdateServiceDomainPrimary :one
UPDATE service_domains
SET is_primary = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, service_id, domain, is_primary, status, last_error, last_reconciled_at, ready_at, created_at, updated_at
`

type UpdateServiceDomainPrimaryParams struct {
	ID        string `json:"id"`
	IsPrimary bool   `json:"is_primary"`
}

func (q *Queries) UpdateServiceDomainPrimary(ctx context.Context, arg UpdateServiceDomainPrimaryParams) (ServiceDomain, error) {
	row := q.db.QueryRow(ctx, updateServiceDomainPrimary, arg.ID, arg.IsPrimary)
	var i ServiceDomain
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Domain,
		&i.IsPrimary,
		&i.Status,
		&i.LastError,
		&i.LastReconciledAt,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
