// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: servers.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServer = `-- name: CreateServer :one
INSERT INTO servers (name, host, port, ssh_user, ssh_key_id, workspace_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, host, port, ssh_user, ssh_key_id, workspace_id, proxy_status, proxy_mode, proxy_last_checked_at, proxy_last_error, created_at
`

type CreateServerParams struct {
	Name        string `json:"name"`
	Host        string `json:"host"`
	Port        int32  `json:"port"`
	SshUser     string `json:"ssh_user"`
	SshKeyID    string `json:"ssh_key_id"`
	WorkspaceID string `json:"workspace_id"`
}

type CreateServerRow struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Host               string             `json:"host"`
	Port               int32              `json:"port"`
	SshUser            string             `json:"ssh_user"`
	SshKeyID           string             `json:"ssh_key_id"`
	WorkspaceID        string             `json:"workspace_id"`
	ProxyStatus        string             `json:"proxy_status"`
	ProxyMode          string             `json:"proxy_mode"`
	ProxyLastCheckedAt pgtype.Timestamptz `json:"proxy_last_checked_at"`
	ProxyLastError     pgtype.Text        `json:"proxy_last_error"`
	CreatedAt          time.Time          `json:"created_at"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (CreateServerRow, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.SshUser,
		arg.SshKeyID,
		arg.WorkspaceID,
	)
	var i CreateServerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.WorkspaceID,
		&i.ProxyStatus,
		&i.ProxyMode,
		&i.ProxyLastCheckedAt,
		&i.ProxyLastError,
		&i.CreatedAt,
	)
	return i, err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, name, host, port, ssh_user, ssh_key_id, workspace_id, proxy_status, proxy_mode, proxy_last_checked_at, proxy_last_error, created_at
FROM servers WHERE id = $1
`

type GetServerByIDRow struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Host               string             `json:"host"`
	Port               int32              `json:"port"`
	SshUser            string             `json:"ssh_user"`
	SshKeyID           string             `json:"ssh_key_id"`
	WorkspaceID        string             `json:"workspace_id"`
	ProxyStatus        string             `json:"proxy_status"`
	ProxyMode          string             `json:"proxy_mode"`
	ProxyLastCheckedAt pgtype.Timestamptz `json:"proxy_last_checked_at"`
	ProxyLastError     pgtype.Text        `json:"proxy_last_error"`
	CreatedAt          time.Time          `json:"created_at"`
}

func (q *Queries) GetServerByID(ctx context.Context, id string) (GetServerByIDRow, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i GetServerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.WorkspaceID,
		&i.ProxyStatus,
		&i.ProxyMode,
		&i.ProxyLastCheckedAt,
		&i.ProxyLastError,
		&i.CreatedAt,
	)
	return i, err
}

const getServerWithKey = `-- name: GetServerWithKey :one
SELECT s.id, s.name, s.host, s.port, s.ssh_user, s.ssh_key_id, s.workspace_id, s.created_at,
       k.private_key
FROM servers s
JOIN ssh_keys k ON k.id = s.ssh_key_id
WHERE s.id = $1
`

type GetServerWithKeyRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Host        string    `json:"host"`
	Port        int32     `json:"port"`
	SshUser     string    `json:"ssh_user"`
	SshKeyID    string    `json:"ssh_key_id"`
	WorkspaceID string    `json:"workspace_id"`
	CreatedAt   time.Time `json:"created_at"`
	PrivateKey  string    `json:"private_key"`
}

func (q *Queries) GetServerWithKey(ctx context.Context, id string) (GetServerWithKeyRow, error) {
	row := q.db.QueryRow(ctx, getServerWithKey, id)
	var i GetServerWithKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.PrivateKey,
	)
	return i, err
}

const listServersByWorkspace = `-- name: ListServersByWorkspace :many
SELECT id, name, host, port, ssh_user, ssh_key_id, workspace_id, proxy_status, proxy_mode, proxy_last_checked_at, proxy_last_error, created_at
FROM servers WHERE workspace_id = $1
ORDER BY created_at DESC
`

type ListServersByWorkspaceRow struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Host               string             `json:"host"`
	Port               int32              `json:"port"`
	SshUser            string             `json:"ssh_user"`
	SshKeyID           string             `json:"ssh_key_id"`
	WorkspaceID        string             `json:"workspace_id"`
	ProxyStatus        string             `json:"proxy_status"`
	ProxyMode          string             `json:"proxy_mode"`
	ProxyLastCheckedAt pgtype.Timestamptz `json:"proxy_last_checked_at"`
	ProxyLastError     pgtype.Text        `json:"proxy_last_error"`
	CreatedAt          time.Time          `json:"created_at"`
}

func (q *Queries) ListServersByWorkspace(ctx context.Context, workspaceID string) ([]ListServersByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listServersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServersByWorkspaceRow{}
	for rows.Next() {
		var i ListServersByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.SshUser,
			&i.SshKeyID,
			&i.WorkspaceID,
			&i.ProxyStatus,
			&i.ProxyMode,
			&i.ProxyLastCheckedAt,
			&i.ProxyLastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTLSPendingServers = `-- name: ListTLSPendingServers :many
SELECT s.id, s.host, s.port, s.ssh_user, k.private_key
FROM servers s
JOIN ssh_keys k ON k.id = s.ssh_key_id
WHERE s.proxy_status = 'tls_pending'
`

type ListTLSPendingServersRow struct {
	ID         string `json:"id"`
	Host       string `json:"host"`
	Port       int32  `json:"port"`
	SshUser    string `json:"ssh_user"`
	PrivateKey string `json:"private_key"`
}

func (q *Queries) ListTLSPendingServers(ctx context.Context) ([]ListTLSPendingServersRow, error) {
	rows, err := q.db.Query(ctx, listTLSPendingServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTLSPendingServersRow{}
	for rows.Next() {
		var i ListTLSPendingServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Port,
			&i.SshUser,
			&i.PrivateKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServerProxyError = `-- name: SetServerProxyError :exec
UPDATE servers
SET proxy_status = $2, proxy_last_checked_at = NOW(), proxy_last_error = $3
WHERE id = $1
`

type SetServerProxyErrorParams struct {
	ID             string      `json:"id"`
	ProxyStatus    string      `json:"proxy_status"`
	ProxyLastError pgtype.Text `json:"proxy_last_error"`
}

func (q *Queries) SetServerProxyError(ctx context.Context, arg SetServerProxyErrorParams) error {
	_, err := q.db.Exec(ctx, setServerProxyError, arg.ID, arg.ProxyStatus, arg.ProxyLastError)
	return err
}

const setServerProxyReady = `-- name: SetServerProxyReady :exec
UPDATE servers
SET proxy_status = $2, proxy_mode = 'managed', proxy_last_checked_at = NOW(), proxy_last_error = NULL
WHERE id = $1
`

type SetServerProxyReadyParams struct {
	ID          string `json:"id"`
	ProxyStatus string `json:"proxy_status"`
}

func (q *Queries) SetServerProxyReady(ctx context.Context, arg SetServerProxyReadyParams) error {
	_, err := q.db.Exec(ctx, setServerProxyReady, arg.ID, arg.ProxyStatus)
	return err
}
