// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one

INSERT INTO services (name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    -- A service created one statement ago has no deployments, so it is always pending.
    TRUE::boolean AS has_pending_changes,
    FALSE::boolean AS has_deployed
`

type CreateServiceParams struct {
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	HostPort      pgtype.Int4 `json:"host_port"`
	ServerID      string      `json:"server_id"`
	WorkspaceID   string      `json:"workspace_id"`
	Kind          string      `json:"kind"`
	ProjectID     string      `json:"project_id"`
	EnvironmentID string      `json:"environment_id"`
}

type CreateServiceRow struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	Image             string      `json:"image"`
	ContainerName     string      `json:"container_name"`
	ContainerPort     int32       `json:"container_port"`
	HostPort          pgtype.Int4 `json:"host_port"`
	ServerID          string      `json:"server_id"`
	WorkspaceID       string      `json:"workspace_id"`
	Kind              string      `json:"kind"`
	ProjectID         string      `json:"project_id"`
	EnvironmentID     string      `json:"environment_id"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	HasPendingChanges bool        `json:"has_pending_changes"`
	HasDeployed       bool        `json:"has_deployed"`
}

// has_pending_changes is derived, not stored: a service is pending when no
// *successful* deployment has landed at or after its last row change. That
// covers both cases the canvas cares about — never deployed at all, and edited
// since the last deploy. Derived rather than denormalised onto services so it
// cannot drift out of sync with the deployments table, and expressed here
// rather than in the client so the API and the UI can never disagree on what
// "pending" means. idx_deployments_service_id keeps the lookup cheap.
//
// has_deployed rides alongside it purely to tell the two pending cases apart:
// false means the service has never landed on a server (the review dialog says
// "will be added"), true means it is live and edited since ("will be updated").
// Note has_deployed = false implies has_pending_changes = true, so the pair only
// ever expresses three real states.
//
// Domain changes bump services.updated_at through TouchService below, since the
// routing they change lives in the container's labels and only a deploy can
// rewrite those.
//
// Known gap: editing only env vars still does not mark the service pending.
func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (CreateServiceRow, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.Image,
		arg.ContainerName,
		arg.ContainerPort,
		arg.HostPort,
		arg.ServerID,
		arg.WorkspaceID,
		arg.Kind,
		arg.ProjectID,
		arg.EnvironmentID,
	)
	var i CreateServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.ContainerPort,
		&i.HostPort,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasPendingChanges,
		&i.HasDeployed,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    (NOT EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success' AND d.created_at >= services.updated_at))::boolean AS has_pending_changes,
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success'))::boolean AS has_deployed
FROM services WHERE services.id = $1
`

type GetServiceByIDRow struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	Image             string      `json:"image"`
	ContainerName     string      `json:"container_name"`
	ContainerPort     int32       `json:"container_port"`
	HostPort          pgtype.Int4 `json:"host_port"`
	ServerID          string      `json:"server_id"`
	WorkspaceID       string      `json:"workspace_id"`
	Kind              string      `json:"kind"`
	ProjectID         string      `json:"project_id"`
	EnvironmentID     string      `json:"environment_id"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	HasPendingChanges bool        `json:"has_pending_changes"`
	HasDeployed       bool        `json:"has_deployed"`
}

func (q *Queries) GetServiceByID(ctx context.Context, id string) (GetServiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i GetServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.ContainerPort,
		&i.HostPort,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasPendingChanges,
		&i.HasDeployed,
	)
	return i, err
}

const getServiceWithServer = `-- name: GetServiceWithServer :one
SELECT
    s.id, s.name, s.image, s.container_name, s.container_port, s.host_port,
    s.server_id, s.workspace_id, s.kind, s.project_id, s.environment_id,
    s.created_at, s.updated_at,
    (NOT EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = s.id AND d.status = 'success' AND d.created_at >= s.updated_at))::boolean AS has_pending_changes,
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = s.id AND d.status = 'success'))::boolean AS has_deployed,
    srv.host, srv.port AS server_port, srv.ssh_user,
    srv.proxy_status,
    k.private_key
FROM services s
JOIN servers srv ON srv.id = s.server_id
JOIN ssh_keys k ON k.id = srv.ssh_key_id
WHERE s.id = $1
`

type GetServiceWithServerRow struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	Image             string      `json:"image"`
	ContainerName     string      `json:"container_name"`
	ContainerPort     int32       `json:"container_port"`
	HostPort          pgtype.Int4 `json:"host_port"`
	ServerID          string      `json:"server_id"`
	WorkspaceID       string      `json:"workspace_id"`
	Kind              string      `json:"kind"`
	ProjectID         string      `json:"project_id"`
	EnvironmentID     string      `json:"environment_id"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	HasPendingChanges bool        `json:"has_pending_changes"`
	HasDeployed       bool        `json:"has_deployed"`
	Host              string      `json:"host"`
	ServerPort        int32       `json:"server_port"`
	SshUser           string      `json:"ssh_user"`
	ProxyStatus       string      `json:"proxy_status"`
	PrivateKey        string      `json:"private_key"`
}

func (q *Queries) GetServiceWithServer(ctx context.Context, id string) (GetServiceWithServerRow, error) {
	row := q.db.QueryRow(ctx, getServiceWithServer, id)
	var i GetServiceWithServerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.ContainerPort,
		&i.HostPort,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasPendingChanges,
		&i.HasDeployed,
		&i.Host,
		&i.ServerPort,
		&i.SshUser,
		&i.ProxyStatus,
		&i.PrivateKey,
	)
	return i, err
}

const listServicesByEnvironment = `-- name: ListServicesByEnvironment :many
SELECT id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    (NOT EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success' AND d.created_at >= services.updated_at))::boolean AS has_pending_changes,
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success'))::boolean AS has_deployed
FROM services WHERE services.environment_id = $1 ORDER BY created_at DESC
`

type ListServicesByEnvironmentRow struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	Image             string      `json:"image"`
	ContainerName     string      `json:"container_name"`
	ContainerPort     int32       `json:"container_port"`
	HostPort          pgtype.Int4 `json:"host_port"`
	ServerID          string      `json:"server_id"`
	WorkspaceID       string      `json:"workspace_id"`
	Kind              string      `json:"kind"`
	ProjectID         string      `json:"project_id"`
	EnvironmentID     string      `json:"environment_id"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	HasPendingChanges bool        `json:"has_pending_changes"`
	HasDeployed       bool        `json:"has_deployed"`
}

func (q *Queries) ListServicesByEnvironment(ctx context.Context, environmentID string) ([]ListServicesByEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, listServicesByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesByEnvironmentRow{}
	for rows.Next() {
		var i ListServicesByEnvironmentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ContainerName,
			&i.ContainerPort,
			&i.HostPort,
			&i.ServerID,
			&i.WorkspaceID,
			&i.Kind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasPendingChanges,
			&i.HasDeployed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByProject = `-- name: ListServicesByProject :many
SELECT id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    (NOT EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success' AND d.created_at >= services.updated_at))::boolean AS has_pending_changes,
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success'))::boolean AS has_deployed
FROM services WHERE services.project_id = $1 ORDER BY created_at DESC
`

type ListServicesByProjectRow struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	Image             string      `json:"image"`
	ContainerName     string      `json:"container_name"`
	ContainerPort     int32       `json:"container_port"`
	HostPort          pgtype.Int4 `json:"host_port"`
	ServerID          string      `json:"server_id"`
	WorkspaceID       string      `json:"workspace_id"`
	Kind              string      `json:"kind"`
	ProjectID         string      `json:"project_id"`
	EnvironmentID     string      `json:"environment_id"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	HasPendingChanges bool        `json:"has_pending_changes"`
	HasDeployed       bool        `json:"has_deployed"`
}

func (q *Queries) ListServicesByProject(ctx context.Context, projectID string) ([]ListServicesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listServicesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesByProjectRow{}
	for rows.Next() {
		var i ListServicesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ContainerName,
			&i.ContainerPort,
			&i.HostPort,
			&i.ServerID,
			&i.WorkspaceID,
			&i.Kind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasPendingChanges,
			&i.HasDeployed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByWorkspace = `-- name: ListServicesByWorkspace :many
SELECT id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    (NOT EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success' AND d.created_at >= services.updated_at))::boolean AS has_pending_changes,
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success'))::boolean AS has_deployed
FROM services WHERE services.workspace_id = $1 ORDER BY created_at DESC
`

type ListServicesByWorkspaceRow struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	Image             string      `json:"image"`
	ContainerName     string      `json:"container_name"`
	ContainerPort     int32       `json:"container_port"`
	HostPort          pgtype.Int4 `json:"host_port"`
	ServerID          string      `json:"server_id"`
	WorkspaceID       string      `json:"workspace_id"`
	Kind              string      `json:"kind"`
	ProjectID         string      `json:"project_id"`
	EnvironmentID     string      `json:"environment_id"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	HasPendingChanges bool        `json:"has_pending_changes"`
	HasDeployed       bool        `json:"has_deployed"`
}

func (q *Queries) ListServicesByWorkspace(ctx context.Context, workspaceID string) ([]ListServicesByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listServicesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesByWorkspaceRow{}
	for rows.Next() {
		var i ListServicesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ContainerName,
			&i.ContainerPort,
			&i.HostPort,
			&i.ServerID,
			&i.WorkspaceID,
			&i.Kind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasPendingChanges,
			&i.HasDeployed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchService = `-- name: TouchService :exec
UPDATE services SET updated_at = NOW() WHERE id = $1
`

// Marks the service as changed without changing a column on it.
//
// Domains live in their own table, so adding or removing one used to leave
// services.updated_at alone and the service went on looking deployed — while
// the running container still carried the old set of Traefik rules, answering
// for a hostname that had been removed. This is what closes the gap the header
// of this file describes.
func (q *Queries) TouchService(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchService, id)
	return err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $2, image = $3, container_name = $4, container_port = $5, host_port = $6, server_id = $7, updated_at = NOW()
WHERE services.id = $1
RETURNING id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    -- updated_at was just set to NOW(), so nothing can have deployed after it.
    TRUE::boolean AS has_pending_changes,
    -- has_deployed still needs the real lookup: an edited service may well have
    -- deployed before, which is exactly what tells "update" apart from "create".
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success'))::boolean AS has_deployed
`

type UpdateServiceParams struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	HostPort      pgtype.Int4 `json:"host_port"`
	ServerID      string      `json:"server_id"`
}

type UpdateServiceRow struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	Image             string      `json:"image"`
	ContainerName     string      `json:"container_name"`
	ContainerPort     int32       `json:"container_port"`
	HostPort          pgtype.Int4 `json:"host_port"`
	ServerID          string      `json:"server_id"`
	WorkspaceID       string      `json:"workspace_id"`
	Kind              string      `json:"kind"`
	ProjectID         string      `json:"project_id"`
	EnvironmentID     string      `json:"environment_id"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	HasPendingChanges bool        `json:"has_pending_changes"`
	HasDeployed       bool        `json:"has_deployed"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (UpdateServiceRow, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.ContainerName,
		arg.ContainerPort,
		arg.HostPort,
		arg.ServerID,
	)
	var i UpdateServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.ContainerPort,
		&i.HostPort,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasPendingChanges,
		&i.HasDeployed,
	)
	return i, err
}
