// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one

INSERT INTO services (name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    FALSE::boolean AS has_deployed
`

type CreateServiceParams struct {
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	HostPort      pgtype.Int4 `json:"host_port"`
	ServerID      string      `json:"server_id"`
	WorkspaceID   string      `json:"workspace_id"`
	Kind          string      `json:"kind"`
	ProjectID     string      `json:"project_id"`
	EnvironmentID string      `json:"environment_id"`
}

type CreateServiceRow struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	HostPort      pgtype.Int4 `json:"host_port"`
	ServerID      string      `json:"server_id"`
	WorkspaceID   string      `json:"workspace_id"`
	Kind          string      `json:"kind"`
	ProjectID     string      `json:"project_id"`
	EnvironmentID string      `json:"environment_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	HasDeployed   bool        `json:"has_deployed"`
}

// has_deployed is derived, not stored: true once at least one deployment of the
// service has succeeded. It is what tells the two undeployed states apart —
// false means the service has never landed on a server (the review dialog says
// "will be added"), true means it is live ("will be updated").
// idx_deployments_service_id keeps the lookup cheap.
//
// Whether a service is *pending* is deliberately not here. It used to be: a
// subquery comparing services.updated_at against the last successful deploy.
// That asked "was this row edited since", which is a different question from
// "does the server still match", and the two came apart in both directions —
// env vars and domains live in their own tables and never moved updated_at, so
// edits went unmarked, while an edit made and undone left the row marked
// forever. Pending is now a comparison between the service's current config and
// the config its last successful deployment actually shipped, which is the only
// form of the question that can also say what differs. See db/service_config.go.
func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (CreateServiceRow, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.Image,
		arg.ContainerName,
		arg.ContainerPort,
		arg.HostPort,
		arg.ServerID,
		arg.WorkspaceID,
		arg.Kind,
		arg.ProjectID,
		arg.EnvironmentID,
	)
	var i CreateServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.ContainerPort,
		&i.HostPort,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasDeployed,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success'))::boolean AS has_deployed
FROM services WHERE services.id = $1
`

type GetServiceByIDRow struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	HostPort      pgtype.Int4 `json:"host_port"`
	ServerID      string      `json:"server_id"`
	WorkspaceID   string      `json:"workspace_id"`
	Kind          string      `json:"kind"`
	ProjectID     string      `json:"project_id"`
	EnvironmentID string      `json:"environment_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	HasDeployed   bool        `json:"has_deployed"`
}

func (q *Queries) GetServiceByID(ctx context.Context, id string) (GetServiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i GetServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.ContainerPort,
		&i.HostPort,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasDeployed,
	)
	return i, err
}

const getServiceWithServer = `-- name: GetServiceWithServer :one
SELECT
    s.id, s.name, s.image, s.container_name, s.container_port, s.host_port,
    s.server_id, s.workspace_id, s.kind, s.project_id, s.environment_id,
    s.created_at, s.updated_at,
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = s.id AND d.status = 'success'))::boolean AS has_deployed,
    srv.host, srv.port AS server_port, srv.ssh_user,
    srv.proxy_status,
    k.private_key
FROM services s
JOIN servers srv ON srv.id = s.server_id
JOIN ssh_keys k ON k.id = srv.ssh_key_id
WHERE s.id = $1
`

type GetServiceWithServerRow struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	HostPort      pgtype.Int4 `json:"host_port"`
	ServerID      string      `json:"server_id"`
	WorkspaceID   string      `json:"workspace_id"`
	Kind          string      `json:"kind"`
	ProjectID     string      `json:"project_id"`
	EnvironmentID string      `json:"environment_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	HasDeployed   bool        `json:"has_deployed"`
	Host          string      `json:"host"`
	ServerPort    int32       `json:"server_port"`
	SshUser       string      `json:"ssh_user"`
	ProxyStatus   string      `json:"proxy_status"`
	PrivateKey    string      `json:"private_key"`
}

func (q *Queries) GetServiceWithServer(ctx context.Context, id string) (GetServiceWithServerRow, error) {
	row := q.db.QueryRow(ctx, getServiceWithServer, id)
	var i GetServiceWithServerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.ContainerPort,
		&i.HostPort,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasDeployed,
		&i.Host,
		&i.ServerPort,
		&i.SshUser,
		&i.ProxyStatus,
		&i.PrivateKey,
	)
	return i, err
}

const listServicesByEnvironment = `-- name: ListServicesByEnvironment :many
SELECT id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success'))::boolean AS has_deployed
FROM services WHERE services.environment_id = $1 ORDER BY created_at DESC
`

type ListServicesByEnvironmentRow struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	HostPort      pgtype.Int4 `json:"host_port"`
	ServerID      string      `json:"server_id"`
	WorkspaceID   string      `json:"workspace_id"`
	Kind          string      `json:"kind"`
	ProjectID     string      `json:"project_id"`
	EnvironmentID string      `json:"environment_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	HasDeployed   bool        `json:"has_deployed"`
}

func (q *Queries) ListServicesByEnvironment(ctx context.Context, environmentID string) ([]ListServicesByEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, listServicesByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesByEnvironmentRow{}
	for rows.Next() {
		var i ListServicesByEnvironmentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ContainerName,
			&i.ContainerPort,
			&i.HostPort,
			&i.ServerID,
			&i.WorkspaceID,
			&i.Kind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasDeployed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByProject = `-- name: ListServicesByProject :many
SELECT id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success'))::boolean AS has_deployed
FROM services WHERE services.project_id = $1 ORDER BY created_at DESC
`

type ListServicesByProjectRow struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	HostPort      pgtype.Int4 `json:"host_port"`
	ServerID      string      `json:"server_id"`
	WorkspaceID   string      `json:"workspace_id"`
	Kind          string      `json:"kind"`
	ProjectID     string      `json:"project_id"`
	EnvironmentID string      `json:"environment_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	HasDeployed   bool        `json:"has_deployed"`
}

func (q *Queries) ListServicesByProject(ctx context.Context, projectID string) ([]ListServicesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listServicesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesByProjectRow{}
	for rows.Next() {
		var i ListServicesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ContainerName,
			&i.ContainerPort,
			&i.HostPort,
			&i.ServerID,
			&i.WorkspaceID,
			&i.Kind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasDeployed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByWorkspace = `-- name: ListServicesByWorkspace :many
SELECT id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success'))::boolean AS has_deployed
FROM services WHERE services.workspace_id = $1 ORDER BY created_at DESC
`

type ListServicesByWorkspaceRow struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	HostPort      pgtype.Int4 `json:"host_port"`
	ServerID      string      `json:"server_id"`
	WorkspaceID   string      `json:"workspace_id"`
	Kind          string      `json:"kind"`
	ProjectID     string      `json:"project_id"`
	EnvironmentID string      `json:"environment_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	HasDeployed   bool        `json:"has_deployed"`
}

func (q *Queries) ListServicesByWorkspace(ctx context.Context, workspaceID string) ([]ListServicesByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listServicesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesByWorkspaceRow{}
	for rows.Next() {
		var i ListServicesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ContainerName,
			&i.ContainerPort,
			&i.HostPort,
			&i.ServerID,
			&i.WorkspaceID,
			&i.Kind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasDeployed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $2, image = $3, container_name = $4, container_port = $5, host_port = $6, server_id = $7, updated_at = NOW()
WHERE services.id = $1
RETURNING id, name, image, container_name, container_port, host_port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at,
    (EXISTS (SELECT 1 FROM deployments d WHERE d.service_id = services.id AND d.status = 'success'))::boolean AS has_deployed
`

type UpdateServiceParams struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	HostPort      pgtype.Int4 `json:"host_port"`
	ServerID      string      `json:"server_id"`
}

type UpdateServiceRow struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Image         string      `json:"image"`
	ContainerName string      `json:"container_name"`
	ContainerPort int32       `json:"container_port"`
	HostPort      pgtype.Int4 `json:"host_port"`
	ServerID      string      `json:"server_id"`
	WorkspaceID   string      `json:"workspace_id"`
	Kind          string      `json:"kind"`
	ProjectID     string      `json:"project_id"`
	EnvironmentID string      `json:"environment_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	HasDeployed   bool        `json:"has_deployed"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (UpdateServiceRow, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.ContainerName,
		arg.ContainerPort,
		arg.HostPort,
		arg.ServerID,
	)
	var i UpdateServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.ContainerPort,
		&i.HostPort,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasDeployed,
	)
	return i, err
}
