// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlcgen

import (
	"context"
	"time"
)

const createService = `-- name: CreateService :one
INSERT INTO services (name, image, container_name, port, server_id, workspace_id, kind, project_id, environment_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, image, container_name, port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at
`

type CreateServiceParams struct {
	Name          string `json:"name"`
	Image         string `json:"image"`
	ContainerName string `json:"container_name"`
	Port          int32  `json:"port"`
	ServerID      string `json:"server_id"`
	WorkspaceID   string `json:"workspace_id"`
	Kind          string `json:"kind"`
	ProjectID     string `json:"project_id"`
	EnvironmentID string `json:"environment_id"`
}

type CreateServiceRow struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Image         string    `json:"image"`
	ContainerName string    `json:"container_name"`
	Port          int32     `json:"port"`
	ServerID      string    `json:"server_id"`
	WorkspaceID   string    `json:"workspace_id"`
	Kind          string    `json:"kind"`
	ProjectID     string    `json:"project_id"`
	EnvironmentID string    `json:"environment_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (CreateServiceRow, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.Image,
		arg.ContainerName,
		arg.Port,
		arg.ServerID,
		arg.WorkspaceID,
		arg.Kind,
		arg.ProjectID,
		arg.EnvironmentID,
	)
	var i CreateServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.Port,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, image, container_name, port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at
FROM services WHERE id = $1
`

type GetServiceByIDRow struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Image         string    `json:"image"`
	ContainerName string    `json:"container_name"`
	Port          int32     `json:"port"`
	ServerID      string    `json:"server_id"`
	WorkspaceID   string    `json:"workspace_id"`
	Kind          string    `json:"kind"`
	ProjectID     string    `json:"project_id"`
	EnvironmentID string    `json:"environment_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) GetServiceByID(ctx context.Context, id string) (GetServiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i GetServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.Port,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceWithServer = `-- name: GetServiceWithServer :one
SELECT
    s.id, s.name, s.image, s.container_name, s.port,
    s.server_id, s.workspace_id, s.kind, s.project_id, s.environment_id,
    s.created_at, s.updated_at,
    srv.host, srv.port AS server_port, srv.ssh_user,
    srv.proxy_status,
    k.private_key
FROM services s
JOIN servers srv ON srv.id = s.server_id
JOIN ssh_keys k ON k.id = srv.ssh_key_id
WHERE s.id = $1
`

type GetServiceWithServerRow struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Image         string    `json:"image"`
	ContainerName string    `json:"container_name"`
	Port          int32     `json:"port"`
	ServerID      string    `json:"server_id"`
	WorkspaceID   string    `json:"workspace_id"`
	Kind          string    `json:"kind"`
	ProjectID     string    `json:"project_id"`
	EnvironmentID string    `json:"environment_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Host          string    `json:"host"`
	ServerPort    int32     `json:"server_port"`
	SshUser       string    `json:"ssh_user"`
	ProxyStatus   string    `json:"proxy_status"`
	PrivateKey    string    `json:"private_key"`
}

func (q *Queries) GetServiceWithServer(ctx context.Context, id string) (GetServiceWithServerRow, error) {
	row := q.db.QueryRow(ctx, getServiceWithServer, id)
	var i GetServiceWithServerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.Port,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Host,
		&i.ServerPort,
		&i.SshUser,
		&i.ProxyStatus,
		&i.PrivateKey,
	)
	return i, err
}

const listServicesByEnvironment = `-- name: ListServicesByEnvironment :many
SELECT id, name, image, container_name, port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at
FROM services WHERE environment_id = $1 ORDER BY created_at DESC
`

type ListServicesByEnvironmentRow struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Image         string    `json:"image"`
	ContainerName string    `json:"container_name"`
	Port          int32     `json:"port"`
	ServerID      string    `json:"server_id"`
	WorkspaceID   string    `json:"workspace_id"`
	Kind          string    `json:"kind"`
	ProjectID     string    `json:"project_id"`
	EnvironmentID string    `json:"environment_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListServicesByEnvironment(ctx context.Context, environmentID string) ([]ListServicesByEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, listServicesByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesByEnvironmentRow{}
	for rows.Next() {
		var i ListServicesByEnvironmentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ContainerName,
			&i.Port,
			&i.ServerID,
			&i.WorkspaceID,
			&i.Kind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByProject = `-- name: ListServicesByProject :many
SELECT id, name, image, container_name, port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at
FROM services WHERE project_id = $1 ORDER BY created_at DESC
`

type ListServicesByProjectRow struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Image         string    `json:"image"`
	ContainerName string    `json:"container_name"`
	Port          int32     `json:"port"`
	ServerID      string    `json:"server_id"`
	WorkspaceID   string    `json:"workspace_id"`
	Kind          string    `json:"kind"`
	ProjectID     string    `json:"project_id"`
	EnvironmentID string    `json:"environment_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListServicesByProject(ctx context.Context, projectID string) ([]ListServicesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listServicesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesByProjectRow{}
	for rows.Next() {
		var i ListServicesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ContainerName,
			&i.Port,
			&i.ServerID,
			&i.WorkspaceID,
			&i.Kind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByWorkspace = `-- name: ListServicesByWorkspace :many
SELECT id, name, image, container_name, port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at
FROM services WHERE workspace_id = $1 ORDER BY created_at DESC
`

type ListServicesByWorkspaceRow struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Image         string    `json:"image"`
	ContainerName string    `json:"container_name"`
	Port          int32     `json:"port"`
	ServerID      string    `json:"server_id"`
	WorkspaceID   string    `json:"workspace_id"`
	Kind          string    `json:"kind"`
	ProjectID     string    `json:"project_id"`
	EnvironmentID string    `json:"environment_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListServicesByWorkspace(ctx context.Context, workspaceID string) ([]ListServicesByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listServicesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesByWorkspaceRow{}
	for rows.Next() {
		var i ListServicesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.ContainerName,
			&i.Port,
			&i.ServerID,
			&i.WorkspaceID,
			&i.Kind,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $2, image = $3, container_name = $4, port = $5, server_id = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, name, image, container_name, port, server_id, workspace_id, kind, project_id, environment_id, created_at, updated_at
`

type UpdateServiceParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Image         string `json:"image"`
	ContainerName string `json:"container_name"`
	Port          int32  `json:"port"`
	ServerID      string `json:"server_id"`
}

type UpdateServiceRow struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Image         string    `json:"image"`
	ContainerName string    `json:"container_name"`
	Port          int32     `json:"port"`
	ServerID      string    `json:"server_id"`
	WorkspaceID   string    `json:"workspace_id"`
	Kind          string    `json:"kind"`
	ProjectID     string    `json:"project_id"`
	EnvironmentID string    `json:"environment_id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (UpdateServiceRow, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.ContainerName,
		arg.Port,
		arg.ServerID,
	)
	var i UpdateServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.ContainerName,
		&i.Port,
		&i.ServerID,
		&i.WorkspaceID,
		&i.Kind,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
