// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_env_vars.sql

package sqlcgen

import (
	"context"
)

const deleteServiceEnvVar = `-- name: DeleteServiceEnvVar :exec
DELETE FROM service_env_vars
WHERE service_id = $1 AND key = $2
`

type DeleteServiceEnvVarParams struct {
	ServiceID string `json:"service_id"`
	Key       string `json:"key"`
}

func (q *Queries) DeleteServiceEnvVar(ctx context.Context, arg DeleteServiceEnvVarParams) error {
	_, err := q.db.Exec(ctx, deleteServiceEnvVar, arg.ServiceID, arg.Key)
	return err
}

const getServiceEnvVarsByServiceID = `-- name: GetServiceEnvVarsByServiceID :many
SELECT key, value FROM service_env_vars
WHERE service_id = $1
ORDER BY key ASC
`

type GetServiceEnvVarsByServiceIDRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetServiceEnvVarsByServiceID(ctx context.Context, serviceID string) ([]GetServiceEnvVarsByServiceIDRow, error) {
	rows, err := q.db.Query(ctx, getServiceEnvVarsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetServiceEnvVarsByServiceIDRow{}
	for rows.Next() {
		var i GetServiceEnvVarsByServiceIDRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceEnvVars = `-- name: ListServiceEnvVars :many
SELECT id, service_id, key, value, created_at, updated_at FROM service_env_vars
WHERE service_id = $1
ORDER BY key ASC
`

func (q *Queries) ListServiceEnvVars(ctx context.Context, serviceID string) ([]ServiceEnvVar, error) {
	rows, err := q.db.Query(ctx, listServiceEnvVars, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceEnvVar{}
	for rows.Next() {
		var i ServiceEnvVar
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertServiceEnvVar = `-- name: UpsertServiceEnvVar :one
INSERT INTO service_env_vars (service_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (service_id, key)
DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
RETURNING id, service_id, key, value, created_at, updated_at
`

type UpsertServiceEnvVarParams struct {
	ServiceID string `json:"service_id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
}

func (q *Queries) UpsertServiceEnvVar(ctx context.Context, arg UpsertServiceEnvVarParams) (ServiceEnvVar, error) {
	row := q.db.QueryRow(ctx, upsertServiceEnvVar, arg.ServiceID, arg.Key, arg.Value)
	var i ServiceEnvVar
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
