// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: servers.sql

package sqlcgen

import (
	"context"
	"time"
)

const createServer = `-- name: CreateServer :one
INSERT INTO servers (name, host, port, ssh_user, ssh_key_id, workspace_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, host, port, ssh_user, ssh_key_id, workspace_id, created_at
`

type CreateServerParams struct {
	Name        string `json:"name"`
	Host        string `json:"host"`
	Port        int32  `json:"port"`
	SshUser     string `json:"ssh_user"`
	SshKeyID    string `json:"ssh_key_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.SshUser,
		arg.SshKeyID,
		arg.WorkspaceID,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.WorkspaceID,
		&i.CreatedAt,
	)
	return i, err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, name, host, port, ssh_user, ssh_key_id, workspace_id, created_at
FROM servers WHERE id = $1
`

func (q *Queries) GetServerByID(ctx context.Context, id string) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.WorkspaceID,
		&i.CreatedAt,
	)
	return i, err
}

const getServerWithKey = `-- name: GetServerWithKey :one
SELECT s.id, s.name, s.host, s.port, s.ssh_user, s.ssh_key_id, s.workspace_id, s.created_at,
       k.private_key
FROM servers s
JOIN ssh_keys k ON k.id = s.ssh_key_id
WHERE s.id = $1
`

type GetServerWithKeyRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Host        string    `json:"host"`
	Port        int32     `json:"port"`
	SshUser     string    `json:"ssh_user"`
	SshKeyID    string    `json:"ssh_key_id"`
	WorkspaceID string    `json:"workspace_id"`
	CreatedAt   time.Time `json:"created_at"`
	PrivateKey  string    `json:"private_key"`
}

func (q *Queries) GetServerWithKey(ctx context.Context, id string) (GetServerWithKeyRow, error) {
	row := q.db.QueryRow(ctx, getServerWithKey, id)
	var i GetServerWithKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.SshUser,
		&i.SshKeyID,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.PrivateKey,
	)
	return i, err
}

const listServersByWorkspace = `-- name: ListServersByWorkspace :many
SELECT id, name, host, port, ssh_user, ssh_key_id, workspace_id, created_at
FROM servers WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListServersByWorkspace(ctx context.Context, workspaceID string) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.SshUser,
			&i.SshKeyID,
			&i.WorkspaceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
