// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, workspace_id, workspace_role, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	Token         string    `json:"token"`
	UserID        string    `json:"user_id"`
	WorkspaceID   string    `json:"workspace_id"`
	WorkspaceRole string    `json:"workspace_role"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.Token,
		arg.UserID,
		arg.WorkspaceID,
		arg.WorkspaceRole,
		arg.ExpiresAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const extendSession = `-- name: ExtendSession :one
UPDATE sessions
SET expires_at = LEAST(NOW() + $1::interval, created_at + $2::interval)
WHERE token = $3 AND expires_at > NOW()
RETURNING expires_at
`

type ExtendSessionParams struct {
	IdleTimeout      pgtype.Interval `json:"idle_timeout"`
	AbsoluteLifetime pgtype.Interval `json:"absolute_lifetime"`
	Token            string          `json:"token"`
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, extendSession, arg.IdleTimeout, arg.AbsoluteLifetime, arg.Token)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getSession = `-- name: GetSession :one
SELECT token, user_id, workspace_id, workspace_role, created_at, expires_at
FROM sessions WHERE token = $1 AND expires_at > NOW()
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.WorkspaceID,
		&i.WorkspaceRole,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
