// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ssh_keys.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSSHKey = `-- name: CreateSSHKey :one
INSERT INTO ssh_keys (name, private_key, workspace_id) VALUES ($1, $2, $3)
RETURNING id, name, private_key, workspace_id, created_at
`

type CreateSSHKeyParams struct {
	Name        string `json:"name"`
	PrivateKey  string `json:"private_key"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, createSSHKey, arg.Name, arg.PrivateKey, arg.WorkspaceID)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateKey,
		&i.WorkspaceID,
		&i.CreatedAt,
	)
	return i, err
}

const getSSHKeyByID = `-- name: GetSSHKeyByID :one
SELECT id, name, private_key, workspace_id, created_at
FROM ssh_keys WHERE id = $1
`

func (q *Queries) GetSSHKeyByID(ctx context.Context, id string) (SshKey, error) {
	row := q.db.QueryRow(ctx, getSSHKeyByID, id)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrivateKey,
		&i.WorkspaceID,
		&i.CreatedAt,
	)
	return i, err
}

const listSSHKeyMetadataByWorkspace = `-- name: ListSSHKeyMetadataByWorkspace :many
SELECT id, name, workspace_id, created_at
FROM ssh_keys WHERE workspace_id = $1
ORDER BY created_at DESC
`

type ListSSHKeyMetadataByWorkspaceRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	WorkspaceID string    `json:"workspace_id"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListSSHKeyMetadataByWorkspace(ctx context.Context, workspaceID string) ([]ListSSHKeyMetadataByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listSSHKeyMetadataByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSSHKeyMetadataByWorkspaceRow{}
	for rows.Next() {
		var i ListSSHKeyMetadataByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkspaceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSHKeysByWorkspace = `-- name: ListSSHKeysByWorkspace :many
SELECT id, name, private_key, workspace_id, created_at
FROM ssh_keys WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSSHKeysByWorkspace(ctx context.Context, workspaceID string) ([]SshKey, error) {
	rows, err := q.db.Query(ctx, listSSHKeysByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SshKey{}
	for rows.Next() {
		var i SshKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PrivateKey,
			&i.WorkspaceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
